### ISSUE TITLE
Issue with merge from upstream

### ISSUE THREAD

**Issue by en-sc** [riscv/riscv-openocd#1009]
While merging #994, I've selected the wrong option of `rebase and merge`.
As I see it, there are 2 options:
1. Merge these commits again as a part of the next merge from upstream (#1008).
2. Revert the commits (as a squashed revert) and merge again (#1007 is the revert).

I am leaning towards the first option, since this affects the list of commits in the merge, but not the diff.

@JanMatCodasip, @MarekVCodasip, I would like to know your opinion on the matter.

**Comment by JanMatCodasip** [comment]
Hello @en-sc, the option 1 sounds fine to me, too. Thanks.

**Comment by MarekVCodasip** [comment]
First options seems ok to me.

**Comment by en-sc** [comment]
#1008 is merged. The issue is fixed.
