### ISSUE TITLE
automate passing `set arch riscv:rv32` to gdb?

### ISSUE THREAD

**Issue by ilg-ul** [riscv/riscv-openocd#101]
I noticed that when starting GDB for a RISC-V debug session I have to pass a command like:

```
set arch riscv:rv32
```

similarly, when starting debug sessions with ARM devices, setting the architecture is not necessary.

it looks like OpenOCD is able to automatically inform GDB what the architecture is, but this feature is not used for RISC-V devices.

is there anything to do to automate passing the architecture for RISC-V devices too?

**Comment by timsifive** [comment]
This is the same issue as https://github.com/riscv/riscv-binutils-gdb/issues/54 (which is not being worked on :-( ).

**Comment by ilg-ul** [comment]
ok, at least we know the cause.

**Comment by timsifive** [comment]
https://github.com/riscv/riscv-binutils-gdb/issues/54 was fixed.

**Comment by ilg-ul** [comment]
Thank you, Tim.

When do you think you'll have a new official release of GDB and OpenOCD, with all these goodies?

**Comment by timsifive** [comment]
This change is in riscv-tools now.
