### ISSUE TITLE
Use "riscv set_ir dtmcs 0x20000" command can't trigger dmihardreset?

### ISSUE THREAD

**Issue by Alan-19950616** [riscv/riscv-openocd#1052]
I'm debugging a RISCV CPU and I noticed that I can't trigger a dmihardreset using OpenOCD's command, is there a problem here?

This is part of the configuration

```
init
riscv set_ir dtmcs 0x20000
reset
halt
```

**Comment by TommyMurphyTM1234** [comment]
Are you sure that your target implements it? Seems like many implementations do not or, at least, did not in the past:

* https://github.com/riscv/riscv-debug-spec/issues/470

It may help to capture and attach a verbose `openocd -d3` log for analysis.

Note that `dtmcs[17]` is `dtmcs.dmihardreset` in the 0.13 spec but is now `dtmcs.dtmhardreset` in the latest 1.0.0-rc2.1 frozen draft.

**Comment by Alan-19950616** [comment]
I'm sure this feature is implemented on my hardware, the current debug version of the hardware is 0.13

Attaching the log file later

**Comment by TommyMurphyTM1234** [comment]
Are you assuming that this: 
```
riscv set_ir dtmcs 0x20000
```
sets the actual value of `dtmcs`?
The documentation and this issue: 

* https://github.com/riscv-collab/riscv-openocd/pull/345
* https://openocd.org/doc/html/Architecture-and-Core-Commands.html

suggests that it's for setting the IR value or effectively the "address" of the relevant register in the DTM?

**Comment by Alan-19950616** [comment]
Is that my misunderstanding.

How do I write the dtmcs registers correctly? Via configuration file

**Comment by en-sc** [comment]
@Alan-19950616, you can use the following:
```
init
poll disable
irscan <tap name> 0x10
drscan <tap name> 32 0x20000
poll enable
reset
halt
```

**Comment by en-sc** [comment]
You can get `<tap name>` from `jtag names` command. Or just find it in your config file.

**Comment by en-sc** [comment]
A bit of ellaboration:
* `poll disable/enable` is needed, so OpenOCD does not insert poll operations. These would change IR back to `dmi`.
* If the script above fails, try adding `irscan <tap name> 0x11` before `poll enable` to set IR back to `dmi`. Though this should not be needed and should probably be addressed as a bug.

**Comment by Alan-19950616** [comment]
Thanks for the reply, my problem has been solved.

I'll close issue.
