### ISSUE TITLE
riscv013 Invalidate cache function does not invalidate complete progbuf-cache (off by one error?)

### ISSUE THREAD

**Issue by MountaineerGit** [riscv/riscv-openocd#1139]
Is the invalidate cache function missing to set the last item to zero (` progbuf_cache[15] = 0 `) by design (space for some ERET or so?)?

```
int riscv013_invalidate_cached_debug_buffer(...)
{
	for (unsigned int i = 0; i < 15; i++)   // shall be <= 15 and a also a define???
		dm->progbuf_cache[i] = 0;
}
```

Progbuf size is 16: uint32_t progbuf_cache[16];

**Comment by TommyMurphyTM1234** [comment]
Where are you seeing that code?
I just cloned the repo from the top of tree and can't see it anywhere.
```
git clone https://github.com/riscv-collab/riscv-openocd
cd riscv-openocd/src/target/riscv
grep riscv013_invalidate_cached_debug_buffer *
# No results
```

**Comment by TommyMurphyTM1234** [comment]
Did you mean this?

- https://github.com/riscv-collab/riscv-openocd/blob/841b61adf3ff26c89d404d3718f82766bc221d55/src/target/riscv/riscv-013.c#L5276-L5288

**Comment by MountaineerGit** [comment]
Yes, sry, looks like it was renamed to `riscv013_invalidate_cached_progbuf`

**Comment by TommyMurphyTM1234** [comment]
I can't see any special handling for `progbuf[15]` in the code or anything in the spec that would cause this to be treated as an exception to the other 15 bytes of the array so maybe it is an off by one error?

**Comment by JanMatCodasip** [comment]
@MountaineerGit Yes, this is an off-by-one error. The whole `progbuf_cache` should be invalidated. Thank you for reporting it.

Your patch to fix this is very welcome. :)

**Comment by TommyMurphyTM1234** [comment]
PR with proposed fix:

- https://github.com/riscv-collab/riscv-openocd/pull/1140
