### ISSUE TITLE
Issues for write memory progbuf handle busy

### ISSUE THREAD

**Issue by lz-bro** [riscv/riscv-openocd#1159]
When encountering abstract command busy response while writing block, `write_memory_progbuf_handle_busy` will be called.
https://github.com/riscv-collab/riscv-openocd/blob/f9a129271642febac27f93673fd96481aff503ca/src/target/riscv/riscv-013.c#L4728-L4747
It seems that only the final address of the failed write (s0) is being processed here，actually, the entire memory block failed to write.
https://github.com/riscv-collab/riscv-openocd/blob/f9a129271642febac27f93673fd96481aff503ca/src/target/riscv/riscv-013.c#L4650-L4671
Is this a bug, or did I misunderstand.

**Comment by en-sc** [comment]
> It seems that only the final address of the failed write (s0) is being processed here，actually, the entire memory block failed to write.

While writing memory via Program Buffer something similar to the following program is used:
```
sw s1 0(s0)
addi s0 s0 4
ebreak
```
https://github.com/riscv-collab/riscv-openocd/blob/f9a129271642febac27f93673fd96481aff503ca/src/target/riscv/riscv-013.c#L4799-L4807

Therefore write at `s0 - <write size>` was successful (otherwise the increment wouldn't have been executed).

**Comment by lz-bro** [comment]
> > It seems that only the final address of the failed write (s0) is being processed here，actually, the entire memory block failed to write.
> 
> While writing memory via Program Buffer something similar to the following program is used:
> 
> ```
> sw s1 0(s0)
> addi s0 s0 4
> ebreak
> ```
> 
> https://github.com/riscv-collab/riscv-openocd/blob/f9a129271642febac27f93673fd96481aff503ca/src/target/riscv/riscv-013.c#L4799-L4807
> 
> Therefore write at `s0 - <write size>` was successful (otherwise the increment wouldn't have been executed).

```
Debug: 12223 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e816eb81 @05 -> ?; 5i
Debug: 12224 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12225 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 01130001 @04 -> ?; 5i
Debug: 12226 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12227 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 1273f416 @05 -> ?; 5i
Debug: 12228 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12229 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 04023283 @04 -> ?; 5i
Debug: 12230 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12231 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e2163410 @05 -> ?; 5i
Debug: 12232 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12233 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 22f33402 @04 -> ?; 5i
Debug: 12234 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12235 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e002e616 @05 -> ?; 5i
Debug: 12236 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12237 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 300022f3 @04 -> ?; 5i
Debug: 12238 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12239 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f81af012 @05 -> ?; 5i
Debug: 12240 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12241 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w ec0ee406 @04 -> ?; 5i
Debug: 12242 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12243 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e8aae4a6 @05 -> ?; 5i
Debug: 12244 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12245 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e0a2fc1e @04 -> ?; 5i
Debug: 12246 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12247 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f8baf4b6 @05 -> ?; 5i
Debug: 12248 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12249 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f0b2ecae @04 -> ?; 5i
Debug: 12250 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12251 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e94ae546 @05 -> ?; 5i
Debug: 12252 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12253 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e142fcbe @04 -> ?; 5i
Debug: 12254 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12255 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f95af556 @05 -> ?; 5i
Debug: 12256 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12257 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f152ed4e @04 -> ?; 5i
Debug: 12258 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12259 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e9eae5e6 @05 -> ?; 5i
Debug: 12260 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12261 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w e1e2fd5e @04 -> ?; 5i
Debug: 12262 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12263 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f9faf5f6 @05 -> ?; 5i
Debug: 12264 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12265 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w f1f2edee @04 -> ?; 5i
Debug: 12266 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12267 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 25f30001 @05 -> ?; 5i
Debug: 12268 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12269 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 0533fdfe @04 -> ?; 5i
Debug: 12270 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12271 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 80e70000 @05 -> ?; 5i
Debug: 12272 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12273 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 70973400 @04 -> ?; 5i
Debug: 12274 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12275 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 720261e2 @05 -> ?; 5i
Debug: 12276 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12277 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 60a2bae0 @04 -> ?; 5i
Debug: 12278 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12279 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 64a66406 @05 -> ?; 5i
Debug: 12280 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12281 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 73e27342 @04 -> ?; 5i
Debug: 12282 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12283 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 76a67606 @05 -> ?; 5i
Debug: 12284 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12285 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 65e66546 @04 -> ?; 5i
Debug: 12286 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12287 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 68aa680a @05 -> ?; 5i
Debug: 12288 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12289 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 77e67746 @04 -> ?; 5i
Debug: 12290 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12291 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 7aaa7a0a @05 -> ?; 5i
Debug: 12292 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12293 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 69ea694a @04 -> ?; 5i
Debug: 12294 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12295 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 6cae6c0e @05 -> ?; 5i
Debug: 12296 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12297 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 7bea7b4a @04 -> ?; 5i
Debug: 12298 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12299 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 7eae7e0e @05 -> ?; 5i
Debug: 12300 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12301 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 6dee6d4e @04 -> ?; 5i
Debug: 12302 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12303 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 90736292 @05 -> ?; 5i
Debug: 12304 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12305 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 7fee7f4e @04 -> ?; 5i
Debug: 12306 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12307 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 30029073 @05 -> ?; 5i
Debug: 12308 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12309 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 62b23412 @04 -> ?; 5i
Debug: 12310 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12311 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 30200073 @05 -> ?; 5i
Debug: 12312 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12313 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 614272a2 @04 -> ?; 5i
Debug: 12314 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12315 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 00200517 @05 -> ?; 5i
Debug: 12316 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12317 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 00018082 @04 -> ?; 5i
Debug: 12318 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12319 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 00018082 @05 -> ?; 5i
Debug: 12320 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12321 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w b2c50513 @04 -> ?; 5i
Debug: 12322 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12323 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 00000533 @05 -> ?; 5i
Debug: 12324 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12325 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 80824505 @04 -> ?; 5i
Debug: 12326 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12327 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 01801517 @05 -> ?; 5i
Debug: 12328 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12329 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 00018082 @04 -> ?; 5i
Debug: 12330 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12331 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 00018082 @05 -> ?; 5i
Debug: 12332 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12333 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w b1450513 @04 -> ?; 5i
Debug: 12334 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12335 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w b0850513 @05 -> ?; 5i
Debug: 12336 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12337 22001 riscv-013.c:431 riscv_decode_dmi_scan(): 41b w 01801517 @04 -> ?; 5i
Debug: 12338 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12339 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @00 -> + 01801517 @04; 5i
Debug: 12340 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: 
Debug: 12350 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @16 -> + 00000000 @00; 3i
Debug: 12360 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @16 -> + 08000102 @16; 3i
Debug: 12361 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: abstractcs=0x8000102 {datacount=2 progbufsize=8 cmderr=busy}
Debug: 12362 22001 riscv-013.c:4829 write_memory_progbuf_run_batch(): [riscv.cpu.0] Encountered abstract command busy response while writing block M[0x40000418.. 0x40000500)
Debug: 12372 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @16 -> + 00000000 @16; 3i
Debug: 12382 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @16 -> + 08000102 @16; 3i
Debug: 12383 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: abstractcs=0x8000102 {datacount=2 progbufsize=8 cmderr=busy}
Debug: 12393 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00000700 @16 -> + 00000000 @16; 3i
Debug: 12394 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: abstractcs=0x700 {cmderr=other}
Debug: 12404 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @16 -> + 00000700 @16; 3i
Debug: 12405 22001 riscv-013.c:859 increase_ac_busy_delay(): [riscv.cpu.0] dtmcs_idle=1, dmi_busy_delay=3, ac_busy_delay=3
Debug: 12415 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00000000 @18 -> + 00000000 @16; 3i
Debug: 12416 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12426 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @18 -> + 00000000 @18; 3i
Debug: 12427 22001 riscv-013.c:1764 register_read_direct(): [riscv.cpu.0] Reading fp
Debug: 12428 22001 riscv-013.c:937 execute_abstract_command(): [riscv.cpu.0] access register=0x321008 {regno=0x1008 write=arg0 transfer=enabled postexec=disabled aarpostincrement=disabled aarsize=64bit}
Debug: 12438 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00321008 @17 -> + 00000000 @18; 6i
Debug: 12439 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: command=0x321008 {control=0x321008}
Debug: 12449 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @16 -> + 00321008 @17; 3i
Debug: 12459 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @16 -> + 08000002 @16; 3i
Debug: 12460 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: abstractcs=0x8000002 {datacount=2 progbufsize=8}
Debug: 12470 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @05 -> + 00000000 @16; 3i
Debug: 12480 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @05 -> + 00000000 @05; 3i
Debug: 12481 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: 
Debug: 12491 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @04 -> + 00000000 @05; 3i
Debug: 12501 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @04 -> + 40000500 @04; 3i
Debug: 12502 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: 
Debug: 12503 22001 riscv-013.c:1783 register_read_direct(): [riscv.cpu.0] fp = 0x40000500
Debug: 12504 22001 riscv-013.c:4759 write_memory_progbuf_handle_busy(): [riscv.cpu.0] Restarting from 0x40000418
Debug: 12505 22001 riscv-013.c:1735 register_write_direct(): [riscv.cpu.0] Writing 0x40000500 to fp
Debug: 12515 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00000000 @05 -> + 00000000 @04; 3i
Debug: 12516 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12526 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @05 -> + 00000000 @05; 3i
Debug: 12536 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 40000500 @04 -> + 00000000 @05; 3i
Debug: 12537 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12547 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @04 -> + 40000500 @04; 3i
Debug: 12548 22001 riscv-013.c:937 execute_abstract_command(): [riscv.cpu.0] access register=0x331008 {regno=0x1008 write=register transfer=enabled postexec=disabled aarpostincrement=disabled aarsize=64bit}
Debug: 12558 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00331008 @17 -> + 00000000 @04; 6i
Debug: 12559 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: command=0x331008 {control=0x331008}
Debug: 12569 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @16 -> + 00331008 @17; 3i
Debug: 12579 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @16 -> + 08000002 @16; 3i
Debug: 12580 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: abstractcs=0x8000002 {datacount=2 progbufsize=8}
Debug: 12581 22001 riscv-013.c:1754 register_write_direct(): [riscv.cpu.0] fp <- 0x40000500
Debug: 12591 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00000000 @05 -> + 00000000 @16; 3i
Debug: 12592 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12602 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @05 -> + 00000000 @05; 3i
Debug: 12612 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00008082 @04 -> + 00000000 @05; 3i
Debug: 12613 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12623 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @04 -> + 00008082 @04; 3i
Debug: 12624 22001 riscv-013.c:937 execute_abstract_command(): [riscv.cpu.0] access register=0x371009 {regno=0x1009 write=register transfer=enabled postexec=enabled aarpostincrement=disabled aarsize=64bit}
Debug: 12634 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00371009 @17 -> + 00000000 @04; 6i
Debug: 12635 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: command=0x371009 {control=0x371009}
Debug: 12645 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b r 00000000 @16 -> + 00371009 @17; 3i
Debug: 12655 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @16 -> + 08000002 @16; 3i
Debug: 12656 22001 riscv-013.c:428 riscv_decode_dmi_scan(): read: abstractcs=0x8000002 {datacount=2 progbufsize=8}
Debug: 12657 22001 riscv-013.c:3198 log_memory_access64(): M[0x40000500] writes 0x0000000000008082
Debug: 12667 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b w 00000001 @18 -> + 00000000 @16; 3i
Debug: 12668 22001 riscv-013.c:438 riscv_decode_dmi_scan(): write: 
Debug: 12678 22001 riscv-013.c:415 riscv_decode_dmi_scan(): 41b - 00000000 @18 -> + 00000001 @18; 3i
Debug: 12679 22017 server.c:608 sig_handler(): Terminating on Signal 22
```
From my log，write at s0 seems unsuccessful, ultimately leading to overflow，write memory in batch cannot guarantee that the address before s0 was successfully written.
https://github.com/riscv-collab/riscv-openocd/blob/f9a129271642febac27f93673fd96481aff503ca/src/target/riscv/riscv-013.c#L4825-L4838
 `abstractauto.autoexecdata  --  current value in command was written there again` 
 `command.postexec --  Execute the program in the Program Buffer exactly once after
 performing the transfer` 
From the description of the two fields， if the abstract command busy , will the program in the Program Buffer still execute？

**Comment by en-sc** [comment]
@lz-bro, is the reproduction stable?
If so, please, check whether the memory image you were writing was loaded completely.
AFAIK, the easiest way to do so is:
1. Run `load_image <args...>` -- leads to OpenOCD crashing
2. Second run (without `reset` in-between) `verify_image <same args...>`

My assumption is: the last write in the batch results in `abstractcs.cmderr == busy`. Therefore `write_memory_progbuf_startup()` is called with `address_p` equal to the address of an element one past the last one (`0x40000500`). And there is an extra erroneous write:
```
Debug: 12657 22001 riscv-013.c:3198 log_memory_access64(): M[0x40000500] writes 0x0000000000008082
```

**Comment by lz-bro** [comment]
> @lz-bro, is the reproduction stable? If so, please, check whether the memory image you were writing was loaded completely. AFAIK, the easiest way to do so is:
> 
> 1. Run `load_image <args...>` -- leads to OpenOCD crashing
> 2. Second run (without `reset` in-between) `verify_image <same args...>`
> 
> My assumption is: the last write in the batch results in `abstractcs.cmderr == busy`. Therefore `write_memory_progbuf_startup()` is called with `address_p` equal to the address of an element one past the last one (`0x40000500`). And there is an extra erroneous write:
> 
> ```
> Debug: 12657 22001 riscv-013.c:3198 log_memory_access64(): M[0x40000500] writes 0x0000000000008082
> ```

@en-sc I failed to use load_image command, so read memory directly.  It not look like that the last write in the batch results in `abstractcs.cmderr == busy.` 
![image](https://github.com/user-attachments/assets/6dd0b23c-dc05-48da-b6e9-9116fbd0590c)

```
Debug: 11578 21970 riscv-013.c:3198 log_memory_access64(): M[0x40000400] writes 0x0032c2930032f293
Debug: 11579 21970 riscv-013.c:3198 log_memory_access64(): M[0x40000408] writes 0x000102b300028763

Debug: 11868 21986 riscv-013.c:4829 write_memory_progbuf_run_batch(): [riscv.cpu.0] Encountered abstract command busy response while writing block M[0x40000210.. 0x40000410)

Debug: 12009 21986 riscv-013.c:1783 register_read_direct(): [riscv.cpu.0] fp = 0x40000410
Debug: 12010 21986 riscv-013.c:4759 write_memory_progbuf_handle_busy(): [riscv.cpu.0] Restarting from 0x40000210

Debug: 12163 21986 riscv-013.c:3198 log_memory_access64(): M[0x40000410] writes 0x02b3a029eb820113

------------------------------------------------------------------------------------------------------------------------

Debug: 12212 21986 riscv-013.c:3198 log_memory_access64(): M[0x400004f0] writes 0x00018082b1450513
Debug: 12213 21986 riscv-013.c:3198 log_memory_access64(): M[0x400004f8] writes 0xb085051301801517

Debug: 12362 22001 riscv-013.c:4829 write_memory_progbuf_run_batch(): [riscv.cpu.0] Encountered abstract command busy response while writing block M[0x40000418.. 0x40000500)

Debug: 12503 22001 riscv-013.c:1783 register_read_direct(): [riscv.cpu.0] fp = 0x40000500
Debug: 12504 22001 riscv-013.c:4759 write_memory_progbuf_handle_busy(): [riscv.cpu.0] Restarting from 0x40000418

Debug: 12657 22001 riscv-013.c:3198 log_memory_access64(): M[0x40000500] writes 0x0000000000008082

```

**Comment by en-sc** [comment]
@lz-bro:
1. What is the version of OpenOCD you are using to reproduce this issue?
2. Please, post a complete `-d3` log of both memory write and read. The memory image would also be very helpful (to understand what are the expected values).

**Comment by lz-bro** [comment]
> @lz-bro:
> 
> 1. What is the version of OpenOCD you are using to reproduce this issue?
> 2. Please, post a complete `-d3` log of both memory write and read. The memory image would also be very helpful (to understand what are the expected values).

commit was 687f00c06055026331fa34250dcb05c9f652c361, and OpenOCD will be no crush when using the latest version.
It seems that this  #1087  has eliminated this issue.
[ocd.log](https://github.com/user-attachments/files/17647057/ocd.log)
[ocd-read.log](https://github.com/user-attachments/files/17656823/ocd-read.log)

**Comment by lz-bro** [comment]
> > @lz-bro:
> > 
> > 1. What is the version of OpenOCD you are using to reproduce this issue?
> > 2. Please, post a complete `-d3` log of both memory write and read. The memory image would also be very helpful (to understand what are the expected values).
> 
> commit was [687f00c](https://github.com/riscv-collab/riscv-openocd/commit/687f00c06055026331fa34250dcb05c9f652c361), and OpenOCD will be no crush when using the latest version. It seems that this #1087 has eliminated this issue. [ocd.log](https://github.com/user-attachments/files/17647057/ocd.log) [ocd-read.log](https://github.com/user-attachments/files/17656823/ocd-read.log)

@en-sc The latest version of OpenOCD no longer crashes when loading the memory image, but instead reports a "MIS-MATCHED" in the memory block that it encounters an abstract command busy response. 
Openocd report encountered abstract command busy response while writing block M[0x40000418.. 0x40000500)，but  write_memory_progbuf_startup() is called with address_p equal to the address of an element one past the last one (0x40000500). 
Should we restarting from 0x40000418 to handle abstract command busy ？
The content of s0 seems different between abstract access busy and DMI busy：
1.the content of s0 for abstract access busy -- the address of an element one past the last one.
2.the content of s0 for DMI busy -- the address of the failed write.
If not so, it may be a hardware issue.

https://github.com/riscv-collab/riscv-openocd/blob/f9a129271642febac27f93673fd96481aff503ca/src/target/riscv/riscv-013.c#L4645-L4671

**Comment by en-sc** [comment]
> The content of s0 seems different between abstract access busy and DMI busy：
1.the content of s0 for abstract access busy -- the address of an element one past the last one.
2.the content of s0 for DMI busy -- the address of the failed write.

I don't think you are right.

The hart is executing the following in the Program Buffer:
1. store using the address from `s0`
2. increment `s0`
3. ebreak
DMI busy can happen at any moment and does not abort the execution of the Program Buffer. Therefore after the last DMI operation finishes, `s0` is the same as it would have been without the DMI busy error occurring. Now remember that the DMI write that caused DMI busy was the request to write the next element. Therefore the address in `s0` is the address of the failed write (that have not started due to DMI busy).

`abstractcs.cmderr == busy` (shortened to AC busy further) is different. It will abort the execution of Program Buffer (the request to start the next write arrived too early).
There are 3 cases:
1.1 AC busy happens before the store retires -- the store is not finished, `s0` contains the address of the write that failed.
1.2 AC busy happens after the store retires but before the increment retires -- the store is fine, `s0` contains the address of the last successful write.
1.3. AC busy happens after the increment retires --  the store is fine, `s0` contains the address of the next write.

Therefore in cases 1.1 and 1.3 the address in `s0` is the address of the failed write (these are the elements that were not yet written).
The case 1.2 is different. Due to the fact that the store has succeeded but the increment fails `s0` contains the address of the last successful write. Therefore, restarting from this address writes the memory there the second time.
However, in none of the cases the address in `s0` is incremented when the store is not successful.

This makes me believe this is a HW issue.

**Comment by lz-bro** [comment]
> > The content of s0 seems different between abstract access busy and DMI busy：
> > 1.the content of s0 for abstract access busy -- the address of an element one past the last one.
> > 2.the content of s0 for DMI busy -- the address of the failed write.
> 
> I don't think you are right.
> 
> The hart is executing the following in the Program Buffer:
> 
> 1. store using the address from `s0`
> 2. increment `s0`
> 3. ebreak
>    DMI busy can happen at any moment and does not abort the execution of the Program Buffer. Therefore after the last DMI operation finishes, `s0` is the same as it would have been without the DMI busy error occurring. Now remember that the DMI write that caused DMI busy was the request to write the next element. Therefore the address in `s0` is the address of the failed write (that have not started due to DMI busy).
> 
> `abstractcs.cmderr == busy` (shortened to AC busy further) is different. It will abort the execution of Program Buffer (the request to start the next write arrived too early).`abstractcs.cmderr == busy`  There are 3 cases:  1.1 AC busy happens before the store retires -- the store is not finished, `s0` contains the address of the write that failed. 1.2 AC busy happens after the store retires but before the increment retires -- the store is fine, `s0` contains the address of the last successful write. 1.3. AC busy happens after the increment retires -- the store is fine, `s0` contains the address of the next write.
> 
> Therefore in cases 1.1 and 1.3 the address in `s0` is the address of the failed write (these are the elements that were not yet written). The case 1.2 is different. Due to the fact that the store has succeeded but the increment fails `s0` contains the address of the last successful write. Therefore, restarting from this address writes the memory there the second time.However, in none of the cases the address in `s0` is incremented when the store is not successful.
> 
> This makes me believe this is a HW issue.

@en-sc Thank you, I will discuss it with my hardware colleagues

**Comment by lz-bro** [comment]
@en-sc It seems to indicate that `abstractcs.cmderr == busy` will not abort the execution of Program Buffer from debug spec-v1.0.0. 
1. any of these operations fail, cmderr is set and none of the remaining steps are executed. (Fail is not equivalent to busy)
![img_v3_02gh_cc98437a-bdc0-4b8f-87fa-0480b3a47a7g](https://github.com/user-attachments/assets/9d1ec317-3ac7-48d3-848e-f29429e7d37e)
2. A new command still gets to run to completion while busy is set.
![img_v3_02gh_1b9b3f04-093c-46fa-b1c1-3f8e8306868g](https://github.com/user-attachments/assets/2c34c028-54c4-49d7-8967-54049be2cf9b)

**Comment by en-sc** [comment]
@lz-bro, you are right. `abstractcs.cmderr == busy` does not abort the execution.

However, the previous comment:
> 1.the content of s0 for abstract access busy -- the address of an element one past the last one.

Is still incorrect. The next run of program buffer should not start if `abstractcs.cmderr` is not clear [3.14.6. Abstract Control and Status (abstractcs, at 0x16), cmderr field description]:
> No abstract command is started until the value is reset to 0.

Therefore `s0` contains the address from which we need to restart the writes (since the status of the write is unknown) in case of `cmderr == busy`.

**Comment by lz-bro** [comment]
Thanks. I will close this.
