### ISSUE TITLE
Wonky behavior if PROGBUF and DATA aren't contiguous (?)

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#139]
I made an image where the PROGBUF and DATA buff had a 1-word gap between them.

At some point (when programming the flash), I get this assertion firing:

https://github.com/riscv/riscv-openocd/blob/f4165279856cde06739a3b9a3ec54e8ff829fabd/src/target/riscv/riscv-013.c#L1993

As far as I can tell, this function would actually always fail, because I don't see where progbuf_addr is ever getting set.

But it seems this code has been geting called all over the place. So not sure what's up.

Actual failure (ignore line numbers, I have some local changes):

```
Debug: 24751 2708 riscv-013.c:1453 read_memory(): transferring burst starting at address 0x80000000 (previous burst was 0x7ffffffc)
Assertion failed: (info->progbuf_addr != -1), function riscv013_progbuf_addr, file src/target/riscv/riscv-013.c, line 2070.
```

**Comment by timsifive** [comment]
This code is removed in https://github.com/riscv/riscv-openocd/pull/131
