### ISSUE TITLE
compilation error on macOS

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#182]
Not sure if this correlates to a recent change, but current OpenOCD master I cannot build on macOS:

I think this is related to bumping libjaylink submodule.

```
discovery_tcp.c:305:9: error: implicit declaration of function 'select' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                ret = select(sock + 1, &rfds, NULL, NULL, &timeout);

```

**Comment by timsifive** [comment]
That looks busted in OpenOCD. I would suggest to do MacOS by with `./configure --disable-werror`.

**Comment by mwachs5** [comment]
never mind. I just started from a clean checkout and it worked. Must have been something stale

**Comment by codebeautiful** [comment]
well, i complied successful
`./bootstrap`
`./configure CFLAGS=--std=gnu11`
`make -j8`
`sudo make install`

**Comment by filamoon** [comment]
I got the exactly same error on mac and none of the above helped. Please help...
