### ISSUE TITLE
[DSA 4093-1] openocd security update

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-openocd#190]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887488

**Comment by timsifive** [comment]
FWIW, discussion on the mailing list indicates the fix addresses this one particular attack vector, but there are likely many others.

We'll get this fix next time we merge from upstream, which I was planning to do once I get http://openocd.zylin.com/#/c/4312/ merged. I can hurry this up if you think it's important.

**Comment by timsifive** [comment]
It looks like this hasn't actually merged to OpenOCD mainline yet, so we're not getting a fix in PR #205.

**Comment by timsifive** [comment]
OpenOCD mailing list discussion: https://sourceforge.net/p/openocd/mailman/openocd-devel/thread/270e864949d7dcbac4695d42d2b9bba5%40atx.name/
Proposed fix: http://openocd.zylin.com/#/c/4335/

If/when this merges to mainline OpenOCD, we'll get it when we pull in mainline. I don't think this requires separate action on our part.
