### ISSUE TITLE
Can't set HBreaks on non-homogeneous cores

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#194]
In a system with heterogenous cores (for example, one core that is M/U-mode only and other cores that are M/S/U), running with `-rtos riscv` assigns a single `$misa` value for the entire target. This is likely to cause a number of problems so may not be reasonable to expect it to work in all cases, but in particular this one should be easy to fix...

If I want to set an `hbreak` on all the cores, the `tdata1` logic tries to set the M/S/U bits according to the common $misa. On the core with no S mode support it fails and then erases the trigger, which is annoying, since the `hbreak` would work fine.

It's also annoying that GDB doesn't report any sort of failure in this case, it just doesn't actually hit the breakpoint until some other hart hits it.

```
Debug: 82338 130893 riscv-013.c:1055 register_read_direct(): [0] reg[0x7e2] = 0x288000000000104c
Debug: 82339 130893 riscv.c:1571 riscv_get_register_on_hart(): [0] tdata1: 288000000000104c
Debug: 82340 130893 riscv.c:374 maybe_add_trigger_t2(): tdata1=0x288000000000104c
Debug: 82341 130893 riscv.c:379 maybe_add_trigger_t2(): Trigger doesn't support what we need; After writing 0x288000000000105c to tdata1 it contains 0x288000000000104c
Debug: 82342 130893 riscv.c:1557 riscv_set_register_on_hart(): [0] tdata1 <- 0
Debug: 82343 130893 riscv-013.c:1876 riscv013_set_register(): writing 0x0 to register tdata1 on hart 0
```

**Comment by timsifive** [comment]
We cannot in general support heterogeneous cores with -rtos. (The obvious problem is with different XLEN cores.) We should be able to make this particular case work, however.
