### ISSUE TITLE
Should deinit_target() deassert dmactive?

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [riscv/riscv-openocd#200]
After reset the RISC-V debug module signal dmactive is low.
When a debug connection is established openocd asserts dmactive (snippet from riscv-013.c):

```
	/* Reset the Debug Module. */
	dmi_write(target, DMI_DMCONTROL, 0);
	dmi_write(target, DMI_DMCONTROL, DMI_DMCONTROL_DMACTIVE);
	uint32_t dmcontrol = dmi_read(target, DMI_DMCONTROL);
```

When the debug session terminates dmactive stays asserted/high and only gets deasserted on the next power on reset.
Should dmactive be deasserted - presumably in deinit_target() - or is there some specific reason that it 's left asserted after the first debug connection?
Is it perhaps for debug across an ndmreset driven reset of the CPU?

**Comment by mwachs5** [comment]
It is not for debug across ndmreset driven reset.

 I think this is a reasonable request.
