### ISSUE TITLE
Reading registers while the target is running can lead to an assertion failure

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-openocd#201]
@TM1234 noticed that if 'halt' is omitted from the OpenOCD config script, OpenOCD will assertion fail when gdb connects.

The reason is that when gdb connects it asks for a list of registers. Our code will try to read a GPR and (assuming the target does not support reading GPRs through abstract commands) fall into the code that uses the program buffer to read registers. However that code asserts because it doesn't support reading GPRs, because that has to be possible using abstract commands (but not necessarily when the target is running). The solution is to propagate an error in the case where we can't read GPRs (for any reason) using abstract commands.

**Comment by TommyMurphyTM1234** [comment]
Thanks for opening this issue Tim,
