### ISSUE TITLE
Mismatch of format suffix `TARGET_PRIxADDR` and type `riscv_addr_t` 

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-openocd#215]
`TARGET_PRIxADDR PRIx32` format suffix is defined in `src/helper/types.h` as PRIx32 or PRIx64
(depends on definition of `BUILD_TARGET64`) .

In `src/target/riscv/riscv-013.c`  `TARGET_PRIxADDR PRIx32` suffix is used to print values of type `riscv_addr_t` (defined in `src/target/riscv/riscv.h` as `uint64_t`).

In case of `configure --disable-target64 ...` there is a warning (and build error) due to suffix/type mismatch.

**Comment by timsifive** [comment]
Thanks. I'll fix that.
