### ISSUE TITLE
NULL deref in get_target_type

### ISSUE THREAD

**Issue by dlrobertson** [riscv/riscv-openocd#259]
I hit a null deref on the latest master in `get_target_type` in `riscv_deinit_target`. The following is the minimal repro I was able to minimize it to.

```
$ cat sigsegv.cfg
interface remote_bitbang
remote_bitbang_host localhost
remote_bitbang_port 9824

init

jtag newtap riscv cpu -irlen 5 -expected-id 0x10e31913

target create riscv.cpu riscv -chain-position riscv.cpu
$ openocd -f sigsegv.cfg
# another terminal
$ echo "shutdown" | nc 127.0.0.1 4444
```

**Comment by timsifive** [comment]
FWIW, I believe OpenOCD "wants" `init` to be called after taps/targets are created. It shouldn't crash, though.
