### ISSUE TITLE
gdb assumes watchpoints fire after the write happened

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-openocd#295]
The RISC-V spec recommends write triggers fire before the write actually occurred. This causes gdb to not fire on watchpoints, because gdb attempts to only halt when the memory value actually changed. To do that it reads the memory the watchpoint was set at, and if it's the same as when the watchpoint was set then it automatically resumes. (See `case WP_VALUE_NOT_CHANGED` in bpstat_check_watchpoint() in gdb/breakpoint.c.)

Solutions that come to mind:
1. Have OpenOCD single step if it detects this. That makes gdb happy, but now users lose the ability to see what the memory value was before the write happened.
2. Change this gdb behavior when debugging RISC-V targets.

I'm not a fan of any of these.

@craigblackmore FYI.

**Comment by craigblackmore** [comment]
GDB should be able to handle watchpoints that fire before the write happens - ```set_gdbarch_have_nonsteppable_watchpoint``` can be used to tell it to step over them first, but this has not been necessary in the C examples (e.g. below) I have tried (and currently OpenOCD manually steps over them anyway).

```
int main()
{
  int data;
  int t0;
  t0 = 1;
  data = t0;

  return 0;
}
```

```
(gdb) load 
Loading section .init, size 0x7c lma 0x40400000
Loading section .text, size 0x5d0 lma 0x4040007c
Loading section .rodata, size 0x54 lma 0x4040064c
Loading section .eh_frame, size 0x2c lma 0x404006a0
Loading section .data, size 0x434 lma 0x404006cc
Start address 0x40400000, load size 2816
Transfer rate: 3 KB/sec, 563 bytes/write.
(gdb) continue
Continuing.
Note: automatically using hardware breakpoints for read-only addresses.

Breakpoint 1, main () at /home/craig/work/projects/sifive/testing-public/gd
b/gdb/testsuite/gdb.riscv/trigger.c:6
6         t0 = 1;
(gdb) watch data
Hardware watchpoint 2: data
(gdb) continue
Continuing.

Hardware watchpoint 2: data

Old value = 0
New value = 1
```

In ```TriggerStoreAddressInstant ```, the ```bpstat_check_watchpoint()```function is not actually getting called, so I think the problem occurs earlier in ```bpstat_stop_status``` where it seems that GDB isn't even checking the watchpoint.

**Comment by timsifive** [comment]
See also insightful responses at https://sourceware.org/ml/gdb/2018-08/msg00047.html

**Comment by timsifive** [comment]
Thanks, @craigblackmore . I'll do some more digging to see exactly what's happening.

**Comment by timsifive** [comment]
I'm not sure what happened in your test, but if I add
```
--- a/gdb/riscv-tdep.c
+++ b/gdb/riscv-tdep.c
@@ -1435,6 +1435,8 @@ riscv_gdbarch_init (struct gdbarch_info info,
   set_gdbarch_ps_regnum (gdbarch, RISCV_FP_REGNUM);
   set_gdbarch_deprecated_fp_regnum (gdbarch, RISCV_FP_REGNUM);
 
+  set_gdbarch_have_nonsteppable_watchpoint (gdbarch, 1);
+
   registers_init (gdbarch, info);
 
   return gdbarch;
```

then the test starts to pass:
```
(gdb) watch *0x10010468
watch *0x10010468
Hardware watchpoint 4: *0x10010468
(gdb) c
c
Continuing.

Hardware watchpoint 4: *0x10010468

Old value = 64
New value = 1
write_loop () at programs/trigger.S:36
36              addi    t0, t0, 1
```

**Comment by craigblackmore** [comment]
It does look like we should be setting this attribute. For some reason, hw watchpoints are being handled okay for local variables, but if I make ```data``` global in my previous example, it only works with the nonsteppable attribute set.
```
int data;

int main()
{
  int t0;
  t0 = 1;
  data = t0;

  return 0;
}
```

**Comment by timsifive** [comment]
Interesting. As a further complication, the Debug Spec allows the trigger to fire just before, or just after the memory write. The debugger knows which of the two it is, but I'm not sure how we could communicate that to gdb.

As a first step I'll implement support for both versions in spike, so I've got something to test against.

**Comment by mwachs5** [comment]
As someone who is now running into this using our latest OpenOCD, is there a GDB command line workaround for this? Can I call something in GDB to indicate I want to know about watchpoints even if the memory location hasn't changed?

**Comment by aswaterman** [comment]
Looking at the GDB source code, I don't see any way to override this setting on the command line.
