### ISSUE TITLE
This repo depends on unreliable submodule

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#297]
This repo depends on a submodule for jimtcl, located at http://repo.or.cz/r/jimtcl.git. This repo is frequently unavailable when cloning submodules. Is there any reason not to clone this repo to something else (e.g. riscv/jimtcl.git) and point to that version instead?

**Comment by aswaterman** [comment]
agreed

**Comment by timsifive** [comment]
Fine by me. Upstream does occasionally change which version we point to, but I've never noticed any problems from using a mismatched version.

**Comment by mwachs5** [comment]
From the JimTCL page, there is an official mirror we could use instead: 
See http://repo.or.cz/w/jimtcl.git or the github mirror at https://github.com/msteveb/jimtcl

**Comment by mwachs5** [comment]
Fixed by #298
