### ISSUE TITLE
Authorization problem when accessing with riscv-openocd 

### ISSUE THREAD

**Issue by WonHoYoo** [riscv/riscv-openocd#302]
When using riscv-openocd with new git pull version, I just kept seeing the message as below

Error: Debugger is not authenticated to target Debug Module. (dmstatus=0x0). Use `riscv authdata_read` and `riscv authdata_write` commands to authenticate.

The thing that I just got confused is in riscv debug information the authentication state could appear in dmstatus which in my state shows the value 0x30c82. 
The value in bit 7 is authenticated and set 1, which must stand for the riscv has authenticated the debugger to do debug. how could this error message came out even the dmstatus state shows authenticated to target Debug Module?

**Comment by timsifive** [comment]
In the error message you got, dmstatus is 0. This sounds like there might be a low-level connectivity issue (eg. JTAG not plugged in right).
