### ISSUE TITLE
E31 hart0 cannot be halted

### ISSUE THREAD

**Issue by aignacio** [riscv/riscv-openocd#305]
Hello,
I'm trying to debug the E31 coreplex IP from SiFive team, and it seems unexpected behavior from target because it cannot be halted but as soon as I understand, the openOCD could talk with debug unit and can read some registers of control. Does anybody had the same problem before? 
..please check the log attached from line 219                         
[log_openocd.txt](https://github.com/riscv/riscv-openocd/files/2450399/log_openocd.txt)

**Comment by timsifive** [comment]
The log shows that OpenOCD sets the haltreq bit, but the hart never actually halts (allrunning stays high, anyhalted stays low). I would guess this is some problem with your target, and not with OpenOCD. https://forums.sifive.com/ is probably the best place to get help with SiFive IP/hardware.

**Comment by aignacio** [comment]
Hello @timsifive, thanks for the answer, I'm afraid of this would be hardware issue because I'm testing my  own SoC with E31 RTL evaluation. Also about the forum, I tried to use it to ask someone about why the core does not fetch more instructions and I think that could be related to the hart not answering the debug module, seems that more people has the same issue according to rtl evaluation of sifive cores, check the link below....tks by now

https://forums.sifive.com/t/problem-during-e31-rtl-evaluation-at-modelsim/1639/3

**Comment by timsifive** [comment]
If the core is not fetching instructions correclty, then debug is not going to work. The Rocket/SiFive implementations rely on the core executing instructions to make debugging happen.
