### ISSUE TITLE
[Question] Is Pulpino implementation supported?

### ISSUE THREAD

**Issue by jaychokshi** [riscv/riscv-openocd#312]
Does this openOcd risc-v SW port support Pulpino risc-v implementation?

Thanks,
Jay

**Comment by timsifive** [comment]
AFAIK Pulpino uses a debug interface that's completely different from what will be the standard for RISC-V, and OpenOCD only supports the (future) standard.

**Comment by jaychokshi** [comment]
Thanks for the response Tim. Appreciate it mate. Where I can find more info about this delta? Are there any link(s) to doc or msg. thread that I could refer to?

**Comment by timsifive** [comment]
I'm not aware of anything that lists the differences. The spec that OpenOCD
implements is at
https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-draft.pdf.
Pulpino did their work when the official effort was just getting off the
ground, and hasn't been part of it.
