### ISSUE TITLE
RVDF FPU F/D register is described only as D

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-openocd#336]
https://github.com/riscv/riscv-openocd/blob/b911e07d75efbfe175657588a64e4ffa67d29ac3/src/target/riscv/riscv.c#L2498

The type of floating point register is defined only as double precision while the same register can be used for single precision values (with a NaN-boxing).
Please use `struct reg_data_type` with `.type_class = REG_TYPE_CLASS_UNION` and `struct reg_data_type_union` .

Thank you

**Comment by timsifive** [comment]
How can I reproduce the problem, and confirm that it is fixed by your suggested change?

**Comment by aka-sps** [comment]
You define the type of 64-bit register only as double precision https://github.com/riscv/riscv-openocd/blob/80ef54dba2411f9354b3793d5832c5d8ad871b4b/src/target/riscv/riscv.c#L2554, while this register can hold NaN-boxed single-precision value too.

Your implementation prints floating point registers only in hexadecimal.

The following definition allows you to output the value of the FPU register as a float / double (and hexadecimal too):

~~~~ c
static reg_data_type IEEE_single_precision_type = {.type = REG_TYPE_IEEE_SINGLE,.id = "ieee_single",};
static reg_data_type IEEE_double_precision_type = {.type = REG_TYPE_IEEE_DOUBLE,.id = "ieee_double",};
static reg_data_type_union_field FPU_S = {.name = "S",.type = &IEEE_single_precision_type};
static reg_data_type_union_field FPU_D = {.name = "D",.type = &IEEE_double_precision_type,.next = &FPU_S};
static reg_data_type_union FPU_D_or_S = {.fields = &FPU_D};
static reg_data_type FPU_D_reg_data_type = {.type = REG_TYPE_ARCH_DEFINED,.id = "Float_D_or_S",.type_class = REG_TYPE_CLASS_UNION,.reg_type_union = &FPU_D_or_S};
~~~~

Perhaps the NaN-box will have to be described as a separate field.

**Comment by timsifive** [comment]
OK, but how can I test this? I assume there's some program or commands I can run through gdb to see the difference you describe.

**Comment by aka-sps** [comment]
Now you can see:
~~~~
(gdb) i r $f0
Invalid register `f0'
(gdb) i r $fa0
fa0            0.073227885178676025     (raw 0x3fb2bf100bff666d)
(gdb) i r $f10
Invalid register `f10'
~~~~
You cannot see single precision values. The canonical names of registers are also absent.

Desired form:
~~~~
(gdb) i r $fa0
fa0            {D = 0x3f826a245049a892, S = 0x5049a892}        {D = 0.0089915120126600502, S = 1.35330714e+010}
(gdb) i r $f0
f0             {D = 0x0, S = 0x0}       {D = 0, S = 0}
~~~~

OpenOCD `reg f10 force` output should look similar.
