### ISSUE TITLE
riscv target: global variables do not allow different cores to be configured independently

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-openocd#343]
See https://github.com/riscv/riscv-openocd/blob/c3c76bfafa6612dc56b3914c9f93eb2a790ef87b/src/target/riscv/riscv.c#L198, https://github.com/riscv/riscv-openocd/blob/c3c76bfafa6612dc56b3914c9f93eb2a790ef87b/src/target/riscv/riscv.c#L200

**Comment by en-sc** [comment]
@aka-sps, I would like to close this one. It was addressed by 6db3ed2c862e04588bf80758acb463a14e9b5ff5

**Comment by en-sc** [comment]
@aka-sps, I'm closing this one. Feel free to reopen, if you have any concerns.
