### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-openocd#356]
https://github.com/riscv/riscv-openocd/blob/9fac2de633ee5c69dced91ff5b92aac0e7836c7e/src/server/gdb_server.c#L2110-L2119

**Comment by timsifive** [comment]
This doesn't look specific to RISC-V or to this fork. It's better to handle this issue upstream at https://sourceforge.net/p/openocd/tickets/.

**Comment by timsifive** [comment]
Closing because it's not RISC-V-specific, and I haven't heard of it affecting anyone either.
