### ISSUE TITLE
Unable to single step via gdb due to wrong PC?

### ISSUE THREAD

**Issue by lbmeng** [riscv/riscv-openocd#360]
When debugging RV64 application in S-mode with SV39 virtual addressing, the GDB sees the PC is not the full PC address with 64-bit width, but a truncated one with only 40-bit. This makes it gdb unable to single step or disassemble the instructions at current PC.

Please check the following gdb output:

> p/x $pc
$19 = 0xe00003159c
> p/x $dpc
$20 = 0xe00003159c
> si
Warning:
Cannot insert breakpoint 0.
Cannot access memory at address 0xe00003159e

The PC can't be 0xe00003159c as it is not a canonical address. The actually PC is 0xffffffe00003159c.

Is this a known issue? From the debug spec, it says the dpc register is MXLEN width, but it does not mention MXLEN is which number.

**Comment by aswaterman** [comment]
Which RISC-V machine are you using?  I ask because there is an erratum on some Rocket-based cores that mis-canonicalizes the value in the `dpc` by zero-extending it.  It was fixed a year ago, but is present in some designs in the wild.

**Comment by lbmeng** [comment]
It's FU540 core on HiFive Unleashed board.

**Comment by aswaterman** [comment]
Yes, that's a known erratum in the silicon, related specifically to the handling of `dpc`.  It would be possible to make an openocd patch that corrects for this bug by unconditionally sign-extending from bit 39 of `dpc`, but it is not an openocd bug.

**Comment by lbmeng** [comment]
Oops, hit a bug of the silicon. :)

Is this erratum publicly documented anywhere?

**Comment by aswaterman** [comment]
I think not all errata are published yet, but this one is, see Sec. 25.4 of https://static.dev.sifive.com/FU540-C000-v1.0.pdf

**Comment by lbmeng** [comment]
Great, I see the errata. Thanks for the quick response!
