### ISSUE TITLE
Execute fence_i twice when resuming

### ISSUE THREAD

**Issue by jhermit** [riscv/riscv-openocd#363]
I found there are two place to execute fence.i, one in the riscv013_on_step_or_resume() and another in the riscv013_step_or_resume_current_hart().
Any particular reason why we have to do the fence.i twice?

**Comment by timsifive** [comment]
I don't think there's a reason. I've already removed one of them in my current working branch.

**Comment by jhermit** [comment]
OK! Thanks!
