### ISSUE TITLE
compilation error on macOS

### ISSUE THREAD

**Issue by filamoon** [riscv/riscv-openocd#378]
I got the same error as #182, but the comments in it did not help.

discovery_tcp.c:305:9: error: implicit declaration of function 'select' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                ret = select(sock + 1, &rfds, NULL, NULL, &timeout);

Fresh checkout, branch riscv. Please help, thanks.

**Comment by filamoon** [comment]
Ok, I solved it by adding one line to src/jtag/drivers/libjaylink/libjaylink/discovery_tcp.c

#include <sys/select.h>

**Comment by TommyMurphyTM1234** [comment]
Might be useful here too?

https://github.com/riscv/riscv-openocd/issues/423#issuecomment-575409664

**Comment by agrobman** [comment]
got the same problem today. Solved this with the same include independently before seeing this ticket. 
@timsifive , could you, please,  just add this include in the file?
Not sure why it compiles on other platforms - the file uses external function without its prototype defined.

Mac uses apple version of  clang instead if GCC, which is more stringent than GCC, I guess.
My peer installed GCC on his Mac, and could compile the tool without this problem ..

**Comment by timsifive** [comment]
@agrobman Can you submit a PR for this?

**Comment by agrobman** [comment]
I can’t , I have other changes in my files

Alex

**Comment by en-sc** [comment]
@filamoon, @agrobman, I would like to close this one. [The fix](https://gitlab.zapb.de/libjaylink/libjaylink/-/commit/28007268ac4f6035041d291e6349ae558c878ed6) is present in currently used version of `libjaylink`.
