### ISSUE TITLE
V11 dbus_read should work more like V13.

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#39]
V11 has the following code in dbus_read, which results in either the  DBUS_OP_READ being sent twice or you getting stale data back (because it is conditioned on address_in).

V13 does it better by changing the second read to a NOP. We should fix V11 code to work the same way.

```
	do {
		status = dbus_scan(target, &address_in, &value, DBUS_OP_READ, address, 0);
		if (status == DBUS_STATUS_BUSY) {
			increase_dbus_busy_delay(target);
		}
	} while (((status == DBUS_STATUS_BUSY) || (address_in != address)) &&
			i++ < 256);
```

**Comment by timsifive** [comment]
Is there an observable advantage to making this change? IIRC the 0.11 spec explicitly says that reads may not have side effects.

**Comment by mwachs5** [comment]
Are you relying on the previous `address` being reported from the last scan (which could have been infinitely long ago) so you don't actually *have* to do the second scan to get the read data? The fact that you might get infinitely old data isn't super intuitive, but if that's your design choice and there aren't any cases where that's actually a problem, maybe a comment is necessary to clarify the intent.
