### ISSUE TITLE
Watchpoints always removed & re-added, even when halted due to bkpoint

### ISSUE THREAD

**Issue by JanMatCodasip** [riscv/riscv-openocd#408]
Please help me review a piece of RISC-V resume-related code in OpenOCD.

In [resume_prep()](https://github.com/riscv/riscv-openocd/blob/riscv/src/target/riscv/riscv.c#L1176), the "watchpoint masquerade" (remove all triggers, step, re-install them and then finally resume) is performed in case an **arbitrary** trigger has been hit (dcsr.cause==2), regardless of whether that trigger is configured as watchpoint or hw breakpoint. 

Note that `target->debug_reason` is set to `DBG_REASON_WATCHPOINT` for any trigger, breakpoints and watchpoints alike.

I believe that in case of plain breakpoints, the watchpoint removal + the other related logic need not be done. By looking at the code, it appears to be bug/unintended and at the very least, it is causing an extra step operation when resuming from a breakpoint.

Thanks,
Jan

**Comment by timsifive** [comment]
It does need to be done even for address execution triggers, which typically have timing=0. Otherwise the trigger will immediately be hit again when resuming and no instructions will be executed.

**Comment by JanMatCodasip** [comment]
Thank you for your reply. 

If I read the code in resume_prep() correctly (link above), it only removes and re-installs  watchpoint triggers, not breakpoints (address execution triggers). 

So to rephrase my original query - 

- Was the original intention to handle both breakpoints and watchpoints the same way in resume_prep()? In that case, the code should perhaps be extended to cover both. I believe, though, that it is not necessary, as breakpoint removal and re-installing is handled by the debugger. My understanding is that only watchpoints need to be handled internally by OpenOCD and breakpoints will be taken care of by the debugger.
- Or was the aim to do the removing and re-installing of triggers for just watchpoints? If that's the case, the watchpoint handling code need not be executed for breakpoints.

Thanks,
Jan

**Comment by timsifive** [comment]
Software breakpoints are already taken care of by gdb, or elsewhere in OpenOCD. This code is only for RISC-V triggers, since it's not always possible to predict whether an instruction will cause them to fire or not.

The aim was to make debugging work the way people expect it to. That means that when somebody steps/runs after being halted by a trigger, at least one instruction is executed. This code exists because we don't always know which triggers were just hit, or which will fire on the next instruction. There is probably a more complicated solution that can achieve the same result by only touching some of the triggers instead of all of them.

**Comment by JanMatCodasip** [comment]
Tim, thanks for your reply.

I understand the generic aim of that code - to make the debugger's step/resume opreations work as people expect.

Per your previous reply, it appears the intent was to temporarily disable **all** triggers on step/resume. Yet that is not what the current code does. It only disables "watchpoint" triggers and completely ignores "hw breakpoint" triggers. So the question is - is this intentional or an oversight?

The reason why no issue popped up here in practice is that debuggers, to my knowledge, do the temporary disabling of breakpoints (both SW&HW) in their own authority. That's why get away with the current OpenOCD code that only deals with watchpoints and ignores hw breakpoints.

But - if we intentionally rely on that behavior of debuggers and wish to stick with the watchpoint-only code for this reason, then an explanatory comment in resume_prep() would be good.

Thanks.

**Comment by timsifive** [comment]
I do not recall the intent of that code beyond "making things work." I believe that internal to OpenOCD, anything that uses RISC-V triggers is referred to as a watchpoint (see set_debug_reason()).

If there's a bug here I'm happy to look at it. If there's a way to break this code without breaking the tests in riscv-tests/debug I'm happy to see about improving the test suite. I don't feel like doing a bunch of work to add a comment.

**Comment by JanMatCodasip** [comment]
> I believe that internal to OpenOCD, anything that uses RISC-V triggers is referred to as a watchpoint (see set_debug_reason()).

This is only partially true. Correct, `set_debug_reason()` will say `DBG_REASON_WATCHPOINT` for all RISC-V triggers ("breakpoints" and "watchpoints" alike).

However, other than that breakpoints and watchpoints are recorded separately (see `breakpoints` vs. `watchpoints` members in `struct target`). That is what provoked my original post, because the code in question in `resume_prep()` is executed for all triggers but then only touches watchpoint triggers (not breakpoints). 

> If there's a bug here I'm happy to look at it. If there's a way to break this code without breaking the tests in riscv-tests/debug I'm happy to see about improving the test suite. I don't feel like doing a bunch of work to add a comment.

After our discussion, I do not believe there is a bug, even though the code in resume_prep() looked suspicious at the first glance (a likely explanation is above - breakpoints are handled by debugger, so we get away with touching just watchpoints, regardless of whether that was the intention or not). 

There may be a room for improvement though - not doing an extra "step" operation in cases it is not needed. I may post it later as a pull request, time permitting. Closing this thread now.

Thank you for your replies.

Jan
