### ISSUE TITLE
RE writing into flash

### ISSUE THREAD

**Issue by ghost** [riscv/riscv-openocd#414]
Dear experts,

I am trying to understand the flash programming using openocd. I noticed in fespi.c, we are able to write chunks of 1mb data to flash. And there is a buffer and from the buffer the data is written to flash. ("data" - refers to application).

I have few questions, please help me in understanding
1. Is the openocd-jtag writing data directly to flash ?
2. Does the openocd-jtag has a driver code running in ram which copies the data section to flash ? (data section refers to bare metal appln)
3. Where does buffer resides ? How does copying a large data using a small ram work ?

note: Currently I have created an appln, that runs in the ram and copies data section to FLASH. Obviously the design is limited by the ram size.

**Comment by timsifive** [comment]
1. No. First it's written to RAM, and then a program ("algorithm") runs on the target to write that data to flash.
2. Yes.
3. It's configured by the user, e.g. with `$_TARGETNAME_0 configure -work-area-phys 0x80000000 -work-area-size 10000 -work-area-backup 1`. See http://openocd.org/doc/html/CPU-Configuration.html for documentation on that. If the buffer can't fit all the data, it repeats the download-to-RAM-then-flash loop as many times as is necessary.
