### ISSUE TITLE
How to cross compile a Windows version openocd

### ISSUE THREAD

**Issue by xfdzjz** [riscv/riscv-openocd#423]
When I was trying to generate a Windows version openocd.exe using cross compiling, but the terminal show me I need a file named windows.h, I can not find the file. And one more question is that I want to generate a win32 version Windows openocd on PC, a normal version is fine, I am not sure how to write the HOST, could you give me some tips? Thanks for your help

**Comment by timsifive** [comment]
I've never built a Windows binary of OpenOCD. I suggest you ask at one of the resources mentioned at http://openocd.org/discussion/

**Comment by TommyMurphyTM1234** [comment]
Bit late to the party but Liviu's xPack Project docker based build scripts for OpenOCD (and other stuff such as Arm and RISC-V embedded/bare metal GCC toolchains) are very useful in this respect and give predictable and reliable results in my experience. 

https://xpack.github.io/openocd/
https://xpack.github.io/openocd/#build-details

By default the scripts build from his repos/snapshots but with a little hacking you can get them to build from alternative sources - e.g. the SiFive OpenOCD fork repo. If you need any guidance post back here.

**Comment by Hzv587** [comment]
> 
> 
> Bit late to the party but Liviu's xPack Project docker based build scripts for OpenOCD (and other stuff such as Arm and RISC-V embedded/bare metal GCC toolchains) are very useful in this respect and give predictable and reliable results in my experience.
> 
> https://xpack.github.io/openocd/
> https://xpack.github.io/openocd/#build-details
> 
> By default the scripts build from his repos/snapshots but with a little hacking you can get them to build from alternative sources - e.g. the SiFive OpenOCD fork repo. If you need any guidance post back here.

Hi, can you please give me more guidance?

**Comment by TommyMurphyTM1234** [comment]
> Hi, can you please give me more guidance?

What do you mean?
Liviu already covers his build process in detail in the links that I posted.

**Comment by TommyMurphyTM1234** [comment]
Oh sorry - I presume you mean about fetching the sources from somewhere other than Liviu's repos? Well you can uncomment these lines to build from the master repos:

https://github.com/xpack-dev-tools/openocd-xpack/blob/xpack/scripts/defs-source.sh#L43

And obviously you can use the same approach to build from any other fork/repo.

**Comment by timsifive** [comment]
Closed due to inactivity.
