### ISSUE TITLE
warning sysctl.h stop compilation

### ISSUE THREAD

**Issue by damiencarrier** [riscv/riscv-openocd#443]
Hello,
I have a warning and cc1 says: all warnings being treated as errors
I don't find how to disable it in the makefile.
What can i do?
Thank you :)

![compilation openocd](https://user-images.githubusercontent.com/57895929/73163083-80c55980-40ef-11ea-93cc-a1d77b11feb4.png)

**Comment by TommyMurphyTM1234** [comment]
Remove -Werror?
I don't get that warning/compilation failure when compiling the RISC-V openocd fork.
Have you modified the code to cause this or something?

**Comment by rtwfroody** [comment]
Specifically, when running configure you can add `--disable-werror` to the command line to ignore warnings.

**Comment by towoe** [comment]
The problem is glibc 2.30 deprecating `sys/sysctl.h`.
@damiencarrier probably uses a distribution which already uses the new glibc version.

Upstream fix http://openocd.zylin.com/#/c/5317/

**Comment by damiencarrier** [comment]
Hello,
Thank you, i re-download openocd and find the -Werror to remove it in the makefile.

**Comment by towoe** [comment]
Yes, removing `-Werrror` will help as it disables the handling of warnings as errors. But this should not be the final solution.
Not sure about the process of importing changes from upstream, but it would make sense to incorporate the upstream fix.
