### ISSUE TITLE
Incorrect physical address translation with `set_enable_virt2phys`

### ISSUE THREAD

**Issue by KireinaHoro** [riscv/riscv-openocd#452]
I'm running into problems with the features from #425 when trying to debug Linux (after `setup_vm()`), the following translation happens:

```
Debug: 3246 5880 riscv.c:1487 riscv_address_translate(): 0xffffffe0004a7d16 -> 0xff000000406a7d16
```

... which results in gdb still reading out all zeroes despite the translation succeeded.  Manually zeroing out the top byte of the translated address will make the read succeed with intended data.

Is there something wrong with the translation logic here?
https://github.com/riscv/riscv-openocd/blob/1449af5bdb99052c2f3bf92747f8438544cd8f3f/src/target/riscv/riscv.c#L1482-L1489

**Comment by timsifive** [comment]
There could be a bug there. Based on your description, it might be the case that somewhere an address is sign-extended where it should be zero-extended.

I wasn't able to easily reproduce this. Did you manage to find a fix? I might have more time to look at this next week.

**Comment by KireinaHoro** [comment]
To reproduce the issue, try debugging Linux kernel.  You should see physical memory correctly before call to `setup_vm`.  If you break on the virtual address which corresponds to the code after the `setup_vm` call, you'll find that the breakpoint is successfully hit, but reading the memory would fail (all zeroes, or `unimp` for code).  The said OpenOCD debug message would appear.

A fix would be very naive to implement, but I don't feel that my method was elegant or even correct:

https://github.com/KireinaHoro/riscv-openocd/commit/03db7213c31ec89c41d240c5bb285ab4cba73cf1

I'd also like to mention that I'm using a modified version of the `use_bscan_tunnel` option on a Zynq UltraScale+ device running Rocket Chip.  Other debug functions (stepping, breakpoints, memory load, etc.) seem to be working just fine, as well as the virtual translation function with the above commit, but I'm not sure if there would be any regressions.  The related OpenOCD commits are as follows:

https://github.com/KireinaHoro/riscv-openocd/commit/cb7f6be16f56a62fc1bdafe0030862e42446e6b2

https://github.com/KireinaHoro/riscv-openocd/commit/11238e1eb4ecb883ee36fcf24668187c782ade5a

**Comment by timsifive** [comment]
I've got a testcase that lets me reproduce this. I'll have a fix soon, or next week.
