### ISSUE TITLE
Hifive1 Rev B support

### ISSUE THREAD

**Issue by KendiMedAmine** [riscv/riscv-openocd#469]
I was trying to connect openocd to the hifive1 Rev B board using the modifications made by #456  and I noticed that the PID in my board is **1061** and not **1051** (using **lsusb**). OpenOCD did not detect the board until I added the **idProduct** attribute **1061**.
Is it an error or did I just miss something ?

**Comment by alistair23** [comment]
I have the same problem.

**Comment by timsifive** [comment]
I assume this can be fixed by adding a line to contrib/60-openocd.rules, but I don't have a board to test this myself.

**Comment by alistair23** [comment]
Upstream OpenOCD has HiFive1 rev B support: https://repo.or.cz/openocd.git/commit/7e78c04f1c275176bdee8f9d2553300218164577

**Comment by timsifive** [comment]
Great! That change is also present in this branch: https://github.com/riscv/riscv-openocd/commit/7e78c04f1c275176bdee8f9d2553300218164577
