### ISSUE TITLE
Potential for null pointer access in riscv_get_registers

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#47]
https://github.com/riscv/riscv-openocd/blob/riscv/src/target/riscv/riscv.c#L418

We don't actually check that target->reg_cache is valid. Apparently GDB might still try to get_reg_list() before target_init(), e.g. if the hardware was powered off when OpenOCD tried to connect. We should return error if the reg_cache is null, or maybe there is a more generic check if the target is not initialized.

**Comment by palmer-dabbelt** [comment]
Fixed b #48
