### ISSUE TITLE
Multiple definitions of bitbang_swd originating from jtag/drivers/bitbang.h

### ISSUE THREAD

**Issue by firephyz** [riscv/riscv-openocd#480]
Bitbang.h seems to be missing an extern declaration on a global struct. I'm not sure if the original author intended the struct to be defined globally in the header file but it is defined with actual values in bitbang.c.

I added 'extern' at the start of the "declaration" in the header file and the source seems to build just fine.

**Comment by hdante** [comment]
I can confirm both the bug and the fix.

**Comment by matsbror** [comment]
I was just hit by the same issue, it seems not be fixed in the source yet.

**Comment by timsifive** [comment]
Can you describe exactly what change you needed to make to get this to compile? bitbang_swd is declared extern in my copy of things.

**Comment by firephyz** [comment]
@matsbror I believe it is fixed if I'm not mistaken: https://github.com/riscv/riscv-openocd/commit/c60252ac2b636c4d99b766a574b9df0966151696

It's apparently only a problem on recent GCC compilers? (starting from GCC 10). The commit above mentions a change to defaulting to -fno-common.

@timsifive Are you having problems compiling recent after recent commits? I think all that needs to be changed is to add the 'extern' keyword in front of the const swd_driver struct in bitbang.h.

**Comment by ryankosta** [comment]
I also just had this same issue with
cc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)

**Comment by timsifive** [comment]
> @timsifive Are you having problems compiling recent after recent commits? I think all that needs to be changed is to add the 'extern' keyword in front of the const swd_driver struct in bitbang.h.

I have no problems building, but I'm still on GCC 9.

bitbang_swd is already defined const in https://github.com/riscv/riscv-openocd/blob/riscv/src/jtag/drivers/bitbang.h#L70

If there is a simple fix that addresses this, I'm happy to merge it.

**Comment by en-sc** [comment]
As mentioned above, the issue is fixed.
