### ISSUE TITLE
tcl server only returns 0x1a when i send "reg" + 0x1a

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-openocd#502]
Hi
   tcl server only returns 0x1a when i send "reg" + 0x1a, is it a bug?
Thanks
Peter

**Comment by TommyMurphyTM1234** [comment]
What is the exact command/code that you're issuing to the openocd tcl interface?
What is your debug target?

**Comment by quantrpeter** [comment]
i found out "ocd_reg pc" can read out the register pc, but "ocd_reg" returns nothing again. I am using java to send out the bytes. If i type "ocd_reg" in telnet terminal, it returns all registers. So only tcl port not working :-(

```
	static void write(OutputStream os, String str) throws IOException {
		os.write(str.getBytes());
		os.write(0x1a);
		os.flush();
	}

	static String read(InputStream is) throws IOException {
		int b;
		b = is.read();
		String str = "";
		while (b != -1 && b != 0x1a) {
			str += (char) b;
			b = is.read();
		}
		return str.trim();
	}
```

**Comment by quantrpeter** [comment]
sorry, it works now. i forget to read some byte from the error stream, so it blocked everything, thanks
