### ISSUE TITLE
missing s0 register

### ISSUE THREAD

**Issue by quantrpeter** [riscv/riscv-openocd#506]
Hi
   The command "reg" is missing S0 register, why?
<img width="1376" alt="Screenshot_17" src="https://user-images.githubusercontent.com/50471577/89852954-a6650c80-dbc2-11ea-91c1-daa947c22a25.png">

Thanks
Peter

**Comment by sorear** [comment]
It's "(8) fp (/32)".  See table 25.1.

**Comment by quantrpeter** [comment]
thanks so much
