### ISSUE TITLE
If read_memory() is called twice one after another, is there something goes wrong?

### ISSUE THREAD

**Issue by Rain0Huang** [riscv/riscv-openocd#51]
In 'riscv-011.c', if 'read_memory' is called after another 'read_memory', the cache line dram_cache[n] will all hit. Then when you execute 'cache_write', an interrupt will be raised as all cache line hit. SO there is the problem, code in debug-ram is run with a interrupt raised without our true-address(dram_cache[4] given after 'cache_write' ) !  And now, the value as address(on dram_cache[4]) is unexpected(depend on the data we read out the last time) .
To avoid this, I force dirty cache line by clear dram_cache[4] as zero before 'cache_write' is called. 
I mean do you think this problem a bug or not? 
@palmer-dabbelt @mwachs5 @ntfreak  @oharboe   etc.
In 'cache_write' this will cause an interrupt to execute code in debug-ram if all cache hit:
dbus_write(target, DMCONTROL, DMCONTROL_HALTNOT | DMCONTROL_INTERRUPT);

**Comment by mwachs5** [comment]
Seems like the same issue reported here https://groups.google.com/a/groups.riscv.org/forum/m/#!topic/debug/DIVd7sLE1a4

Will look into a fix.

**Comment by mwachs5** [comment]
Seems like this case should also check for 'run': https://github.com/riscv/riscv-openocd/blame/riscv/src/target/riscv/riscv-011.c#L873

**Comment by Rain0Huang** [comment]
mwachs5，you are right , 'L873' is the reason cause an interrupt.

**Comment by mwachs5** [comment]
fixed by #52, thanks for reporting the issue
