### ISSUE TITLE
Missing stdexcept include on dtm.cc

### ISSUE THREAD

**Issue by hdante** [riscv/riscv-openocd#512]
Missing stdexcept header file causes the following compilation error:

    (...)
    Removing existing riscv-isa-sim/build directory
    Configuring project riscv-isa-sim
    Building project riscv-isa-sim
    ../fesvr/dtm.cc: In member function ‘uint32_t dtm_t::get_xlen()’:
    ../fesvr/dtm.cc:488:16: error: ‘runtime_error’ is not a member of ‘std’
      488 |     throw std::runtime_error("FESVR DTM Does not support 128-bit");
          |                ^~~~~~~~~~~~~
    ../fesvr/dtm.cc:505:14: error: ‘runtime_error’ is not a member of ‘std’
      505 |   throw std::runtime_error("FESVR DTM can't determine XLEN. Aborting");
          |              ^~~~~~~~~~~~~
    ../fesvr/dtm.cc:506:1: warning: control reaches end of non-void function [-Wreturn-type]
      506 | }

**Comment by timsifive** [comment]
fesvr is part of riscv-fesvr or riscv-isa-sim, not OpenOCD.
