### ISSUE TITLE
x0  actually is NOT cacheable, because it will always read a "ZERO", not the value writen into it

### ISSUE THREAD

**Issue by gxflying** [riscv/riscv-openocd#564]
Hi， sir, I  used the "riscv_set_register/riscv_get_register" to test on gpr "x0" , and get the wrong  result !
because,  the openocd treats the "x0" as a cacheable register and returns the value I wrote by "riscv_set_register" which is not zero
so we can see the log below  read the x0 : 12345678 (cached) , it's a little bit weird, isn't it ?

![Image 45](https://user-images.githubusercontent.com/16956976/104144110-f3147400-53fc-11eb-985e-01124fa40852.jpg)

I  think this is because openocd treat  "x0" as a cacheable register below
https://github.com/riscv/riscv-openocd/blob/d9c73e231e5144e05fe35496975c64817ac54555/src/target/riscv/riscv.c#L3676
and "riscv_get_register->riscv_get_register_on_hart" will return the cached value before the value can be read from the hardware when the register is cacheable
https://github.com/riscv/riscv-openocd/blob/d9c73e231e5144e05fe35496975c64817ac54555/src/target/riscv/riscv.c#L3767
so we get a  non-zero value from "x0"
![Image 45](https://user-images.githubusercontent.com/16956976/104144512-6c609680-53fe-11eb-859b-2e67f8700eeb.jpg)

**Comment by gxflying** [comment]
the pictrue shows below:
"Debug riscv.c : 3770 riscv_get_register_on_hart(): {0} zero: 12345678 (cached)"

by the way,   you can  reproduce this issue by the following tcl command:
```
set X0 0
set res [catch {reg $X0 0x87654321} str_result]  #set the value of x0 to 0x87654321
set res [catch {reg $X0 } str_result]                      # get the value of x0
puts $str_result                                                    # the output is 0x87654321 !!
```

**Comment by timsifive** [comment]
Thanks for catching that. The solution is probably for the code to ignore writes to x0, since they cannot have an effect on RISC-V.
