### ISSUE TITLE
read_memory_progbuf restores wrong value for s2 on increment=0

### ISSUE THREAD

**Issue by MountaineerGit** [riscv/riscv-openocd#632]
riscv-013.c::read_memory_progbuf()

At the beginning: Read of reg s1 into var s2 (content of reg s1 is backed up into s2):
```
	if (increment == 0 && register_read(target, &s2, GDB_REGNO_S1) != ERROR_OK)
		return ERROR_FAIL;
```

On exit restore:
```
	if (increment == 0)
		riscv_set_register(target, GDB_REGNO_S2, s2);  // yes: s2 into s2
```

Proposed fix for the first part: read-out s2 into var s2:
```
	if (increment == 0 && register_read(target, &s2, **GDB_REGNO_S2**) != ERROR_OK)
		return ERROR_FAIL;
```

**Comment by TommyMurphyTM1234** [comment]
Another specific example of the general issue mentioned here?

https://github.com/riscv/riscv-openocd/issues/559#issuecomment-742089261
