### ISSUE TITLE
command 'opneocd' not found

### ISSUE THREAD

**Issue by ghita92** [riscv/riscv-openocd#641]
Hello,
I'm new to riscv, i would like to know what are the paths envirements for openocd.
I installed openocd without any options in the configuration and the command openocd is not recognized.
Thanks

**Comment by TommyMurphyTM1234** [comment]
This is not really a RISC-V issue.
But you need to explain exactly what you did.
You provide no useful info above.

If you are building OpenOCD yourself then git clone, bootstrap, configure and make install should do what you need (at least on GNU/Linux).
And then you just have to ensure that the OpenOCD install bin directory is on your path.

**Comment by ghita92** [comment]
I did install using 
sudo ./bootstrap
sudo ./configure
make
but when then i cannot find openocd.
I have this error Command 'openocd' not found, but can be installed with:

My $path variable is the riskv install path do i set it multiple Time ?
Export path=path to RISCv install$path
Export path=path to openocd install$path ?

**Comment by TommyMurphyTM1234** [comment]
You didn't do make install to install it to the default location.

**Comment by TommyMurphyTM1234** [comment]
> I did install using
> sudo ./bootstrap
> sudo ./configure
> make

You didn't do make install?
Why are you using sudo?

> but when then i cannot find openocd.
> I have this error Command 'openocd' not found, but can be installed with:
> 
> My $path variable is the riskv install path do i set it multiple Time ?
> Export path=path to RISCv install$path
> Export path=path to openocd install$path ?

I don't really understand any of this.
Please try to clarify.

**Comment by ghita92** [comment]
Thanks, i manage to solve the problem by adding the bin path to the $PATH variable.
