### ISSUE TITLE
How to add new commands to read and write custom registers in JTAG DTM TAP？

### ISSUE THREAD

**Issue by ghost** [riscv/riscv-openocd#667]
Hi，
I added a new register at address 0x19 in JTAG DTM TAP Register to help me read and write Debug Bus information when debugging, but I don’t know how to add new commands to openocd to operate it. The operation command is added and it can run successfully, but it only executes a simple print output when the command is received. I don't know how to read and write the data in this register. How can I do it? Can you tell me how to add the operation process and modify the file or function? Any answer is of great help to me.

**Comment by TommyMurphyTM1234** [comment]
You mean that you added a new register to the list in table 6.1 in section 6.1.2?

https://github.com/riscv/riscv-debug-spec/blob/release/riscv-debug-release.pdf

Assuming that to be the case can't you use existing OpenOCD JTAG level commands to interact with your custom register?

https://openocd.org/doc/html/index.html#toc-JTAG-Commands-1

If not then you may need to explain more about your custom register and your requirements.

**Comment by timsifive** [comment]
What Tommy describes should work. You'll probably have to disable polling when you do that, otherwise IR will likely be changed before you get to access DR. See https://openocd.org/doc/html/Server-Configuration.html#Event-Polling

**Comment by ghost** [comment]
Hi @timsifive, @TommyMurphyTM1234,

thanks for your reply.

According to your answers and email from @borneoa, I can read the register data using the following command.

poll off 
irscan  $tapname 0x19 
drscan $tapname $len $data 
poll on

**Comment by TommyMurphyTM1234** [comment]
Glad it helped @OpenEDF
