### ISSUE TITLE
Why is this repo put under https://github.com/riscv/?

### ISSUE THREAD

**Issue by lbmeng** [riscv/riscv-openocd#708]
Shouldn't it be put under

- https://github.com/riscv-collab

or

- https://github.com/riscv-software-src

**Comment by timsifive** [comment]
Because it existed long before riscv-collab and riscv-software-src existed.

**Comment by lbmeng** [comment]
Thanks. Please consider moving this repo to a more appropriate place, just like other repos.

e.g.: opensbi previously existed long before before riscv-collab and riscv-software-src existed but has been moved to riscv-software-src later.

**Comment by TommyMurphyTM1234** [comment]
I presume that the repo is not going to be moved so this issue can be closed?
