### ISSUE TITLE
RISC-V target support doesn't build without --disable-werror

### ISSUE THREAD

**Issue by TM1234** [riscv/riscv-openocd#71]
See here for the original issue report:

https://github.com/gnu-mcu-eclipse/openocd/issues/17

As mentioned there the RISC-V target support code does not build unless --disable-werror is specified at openocd configuration time even though openocd normally (and currently - i.e. openocd 0.10.0+dev development branch) compiles without having to suppress warnings as errors.

Maybe the RISC-V code could be cleaned up to eliminate these warnings?

Thanks.

**Comment by palmer-dabbelt** [comment]
Ya, we should fix it.  @timsifive, do you mind taking a look?

**Comment by ilg-ul** [comment]
I suggest you also try a run on macOS, clang is also not very happy with the code.

**Comment by timsifive** [comment]
Does anybody have experience setting up travis to do 32- and 64-bit builds? That should go a long way towards preventing these problems in the future.
