### ISSUE TITLE
How do I submit code to OpenOCD, or how do I contact OpenOCD officials?

### ISSUE THREAD

**Issue by Johnvcx** [riscv/riscv-openocd#735]

**Comment by TommyMurphyTM1234** [comment]
Do you mean this RISC-V fork of OpenOCD or the upstream/master OpenOCD project (https://openocd.org/)?

To contribute changes to this fork you follow the normal git process for forking, creating a pull request, having the PR reviewed and hopefully accepted etc. Any decent git tutorial will explain how to do this if you're not already familiar with the process.

This fork is periodically sync'd with upstream (both ways) by the main contributors.

The upstream/master OpenOCD project uses a different process for dealing with contributions. See here:

* https://repo.or.cz/openocd.git/blob/HEAD:/HACKING

Or, perhaps if you just want to ask a question or raise an issue you can post it here and the community might be able to help?

**Comment by TommyMurphyTM1234** [comment]
Candidate for closure?
