### ISSUE TITLE
about openocd install question

### ISSUE THREAD

**Issue by crstial-zy** [riscv/riscv-openocd#761]
when i execute teh "make" setup 
mv -f src/.deps/src_libopenocd_la-hello.Tpo src/.deps/src_libopenocd_la-hello.Plo
mv: cannt get"src/.deps/src_libopenocd_la-hello.Tpo" 的file stat(stat): no such file or directory
i want some help, thanks!

**Comment by TommyMurphyTM1234** [comment]
My most recent build worked fine - if you are still having problems then you need to provide more information.

https://github.com/riscv/riscv-openocd/issues/760

**Comment by TommyMurphyTM1234** [comment]
Candidate for closure?
