### ISSUE TITLE
Add "init resethalt" command

### ISSUE THREAD

**Issue by Alan-19950616** [riscv/riscv-openocd#776]
Sometimes Openocd cannot halt the CPU due to a software or hardware problem that accesses the empty address.

At this time If you use “init reset“or"init halt" command in the configuration file, the connection cannot be established.

The "init resethalt" command is designed to solve this problem.

Please help to see if this is reasonable.

add 'init resethalt' command #775

**Comment by JanMatCodasip** [comment]
Hi Alan,

I think if you need to issue additional debug commands to work around specific problem (bug?) in the given hardware, you can do it using commands that OpenOCD already provides. I've further commented on that at https://github.com/riscv/riscv-openocd/pull/775#pullrequestreview-1209581249. Let me know if that would work for you.

**Comment by sifiverobert** [comment]
I agree - adding new comment to battle specific problem is not the way to go.
I recall doing it a script (before 'init' is called).
You can do HW reset (by pin ) and you CAN execute different DM actions (by writing to registers ...).

**Comment by TommyMurphyTM1234** [comment]
The other thing to bear in mind is that, without a compelling case for new functionality such as this, the chances of it being accepted in the "master" OpenOCD project (when the RISC-V OpenOCD changes are periodically upstreamed) will presumably be slim. I am aware of some cases (particularly in FPGA implementations) where things can happen on the hardware side making examine and/or reset [init|halt] difficult but I thought that some recent changes in this context by @timsifive (and maybe others) may have helped make this more reliable?

**Comment by Alan-19950616** [comment]
> Hi Alan,
> 
> I think if you need to issue additional debug commands to work around specific problem (bug?) in the given hardware, you can do it using commands that OpenOCD already provides. I've further commented on that at [#775 (review)](https://github.com/riscv/riscv-openocd/pull/775#pullrequestreview-1209581249). Let me know if that would work for you.

Hi JanMatCodasip, 

I try to use **dmi_write** before **init**, that doesn't seem to be allowed.
![image](https://user-images.githubusercontent.com/46317534/206967765-f857cff2-cc10-489b-94f6-ad3020644672.png)

I try to use **dmi_write** after **init**,  it does do something similar, But it still doesn't solve my problem. The problem I have now is that **init** will fail.
![image](https://user-images.githubusercontent.com/46317534/206970228-7ffdcbd1-3b7e-4b38-bdcb-fcde4ac44a17.png)

**Comment by JanMatCodasip** [comment]
Hi Alan, `riscv dmi_write` & `riscv dmi_read` should be used only after `init`.

You can follow these steps:

1) Call `init`. If your processor is in an incorrect state and won't halt, then the examination (which is part of `init`) will of course fail.
2) After the failed init, you can try to revive your target using `dmi_write` & `dmi_read`.
3) When ready, you can re-examine the target by `<target_name> arp_examine`.

**Comment by Alan-19950616** [comment]
![image](https://user-images.githubusercontent.com/46317534/207032332-e805b600-ed9e-46e2-ba9e-e02c14c2acbb.png)
![image](https://user-images.githubusercontent.com/46317534/207032514-eddc3111-b753-4918-bec2-509e8d23d642.png)

I did what you asked, **arp_examine** does not appear to be successful. 
But **init resethalt** does.

**Comment by timsifive** [comment]
You might have to disable/reenable polling before/after your dmi_write sequence. Otherwise poll() will write to dmcontrol, and clear resethaltreq before you get a chance to issue reset.

Another possible fix is to change reset so that it can execute even when examine() failed.

**Comment by Alan-19950616** [comment]
Hi, timsifive
thank you for your time.

> You might have to disable/reenable polling before/after your dmi_write sequence. Otherwise poll() will write to dmcontrol, and clear resethaltreq before you get a chance to issue reset.

The following figure shows that the CPU has been successfully reset and halted.
![image](https://user-images.githubusercontent.com/46317534/207224087-958b9d2e-3e1f-4de9-8e8b-17531f67fbcc.png)

I did what you said, and it's still the same.
![image](https://user-images.githubusercontent.com/46317534/207224531-fd653b60-a5d3-445f-b039-6b21d96c1669.png)
![image](https://user-images.githubusercontent.com/46317534/207224591-e0f1a4dc-d009-4080-ab9d-37c7a50a4948.png)

> Another possible fix is to change reset so that it can execute even when examine() failed.

What should I do?

**Comment by Alan-19950616** [comment]
Well, in that case then this feature is fine for me to maintain locally.
