### ISSUE TITLE
how to add a riscv-openocd  branches?

### ISSUE THREAD

**Issue by yy172** [riscv/riscv-openocd#781]
how to add a riscv-openocd  branches?

**Comment by JanMatCodasip** [comment]
Hi @yy172, I am sorry, I do not understand your question.

Do you wish to submit a change to riscv-openocd? If so, you can fork the repo then create a branch in your fork. When ready,  your change can be submitted for review as a pull request.

**Comment by TommyMurphyTM1234** [comment]
Candidate for closure?
