### ISSUE TITLE
Add vendor specific CSRs

### ISSUE THREAD

**Issue by madushan1000** [riscv/riscv-openocd#805]
Is there a "proper" way to add vendor specific CSRs to openocd? I have added some T-head specific CSRs here just by modifying `encoding.h` which I'm not sure the proper way to do it. 
https://github.com/riscv/riscv-openocd/compare/riscv...madushan1000:riscv-openocd:thead-csrs

**Comment by JanMatCodasip** [comment]
Hi @madushan1000,
yes, there is a support for custom CSRs already via OpenOCD's configuration command `riscv expose_csrs <...>`. There is no need to modify OpenOCD's source code.

Details can be found in the documentation: https://github.com/riscv/riscv-openocd/blob/riscv/doc/openocd.texi#L10508

**Comment by madushan1000** [comment]
Thanks for the pointer, I'll try it that way, looks much better.
