### ISSUE TITLE
Openocd commands for multithread debugging?

### ISSUE THREAD

**Issue by neanderthal148** [riscv/riscv-openocd#820]
Hi, are there any inbuilt ways of halting, resuming, setting triggers etc. for multithread cores? All commands I have seen so far are only for a single hart.

**Comment by TommyMurphyTM1234** [comment]
Have you read the OpenOCD documentation on SMP and the GDB documentation on how to deal with different threads?

* https://openocd.org/doc/html/Config-File-Guidelines.html#Define-CPU-targets-working-in-SMP
* https://openocd.org/doc/html/GDB-and-OpenOCD.html#Using-OpenOCD-SMP-with-GDB
* https://sourceware.org/gdb/onlinedocs/gdb/Threads.html

What exactly do _you_ mean by "multithread" cores?
Multi-hart cores **are** multithread cores.
"Hart" = "hardware thread".

**Comment by TommyMurphyTM1234** [comment]
Any update @neanderthal148?

**Comment by neanderthal148** [comment]
I was wondering if there were any openocd commands to set hasel, hawindow, hartsel etc. for multi-hart debugging. Right now I'm setting those fields using riscv dmi_write on the debug registers but whenever I use commands like halt, resume, step etc. they seem to be working for hart 0 only regardless of what hart I've selected

**Comment by TommyMurphyTM1234** [comment]
> I was wondering if there were any openocd commands to set hasel, hawindow, hartsel etc. for multi-hart debugging. 

Not as far as I can see:

* https://github.com/riscv/riscv-openocd/blob/a01bd76e5c10eba8bc3481eb7552fb8feab79f91/src/target/riscv/riscv.c#L3824

> Right now I'm setting those fields using riscv dmi_write on the debug registers but whenever I use commands like halt, resume, step etc. they seem to be working for hart 0 only regardless of what hart I've selected

Impossible to comment without more detailed information about what exactly you're trying to do, how you are doing it, and why. E.g. a verbose OpenOCD log generated using `openocd -d3` and maybe using the `telnet` interface to OpenOCD to eliminate "noise" caused by GDB.

I suspect that interfering with stuff like hart selection might conflict with OpenOCD's use of the target for debugging purposes, especially in OpenOCD SMP mode.

**Comment by timsifive** [comment]
> I was wondering if there were any openocd commands to set hasel, hawindow, hartsel etc. for multi-hart debugging. Right now I'm setting those fields using riscv dmi_write on the debug registers but whenever I use commands like halt, resume, step etc. they seem to be working for hart 0 only regardless of what hart I've selected

There are not. Multi-hart debugging can work by configuring multiple targets in the configuration file. See e.g. https://github.com/riscv-software-src/riscv-tests/blob/master/debug/targets/SiFive/HiFiveUnleashed.cfg

**Comment by TommyMurphyTM1234** [comment]
> > I was wondering if there were any openocd commands to set hasel, hawindow, hartsel etc. for multi-hart debugging. Right now I'm setting those fields using riscv dmi_write on the debug registers but whenever I use commands like halt, resume, step etc. they seem to be working for hart 0 only regardless of what hart I've selected
> 
> There are not. Multi-hart debugging can work by configuring multiple targets in the configuration file. See e.g. https://github.com/riscv-software-src/riscv-tests/blob/master/debug/targets/SiFive/HiFiveUnleashed.cfg

Thanks @timsifive - that's what I was referring to here (OpenOCD SMP support).

* https://github.com/riscv/riscv-openocd/issues/820#issuecomment-1479605050

I presume that this is the case? I.e. that tinkering with `hartsel` and the like would probably confuse OpenOCD in SMP mode?

> I suspect that interfering with stuff like hart selection might conflict with OpenOCD's use of the target for debugging purposes, especially in OpenOCD SMP mode.

**Comment by TommyMurphyTM1234** [comment]
Any update @neanderthal148?
