### ISSUE TITLE
OpenOCD Connection time out

### ISSUE THREAD

**Issue by hparpinel** [riscv/riscv-openocd#827]
Hi,

I am using Eclipse CDT and trying to debug with GDB OpenOCD Debugging but I get ^error,msg="localhost:3333: Connection timed out."
The board I am working with is an Arty A7 100T. The board is programmed with the core; the green LED is on. 
My settings are below. What am I missing, do I suppose to start GDB somewhere else?
---MAIN
C/C++ Application: app.elf
---DEBUGGER
Start OpenOCD locally: -f board/arty.cfg -f interface/ftdi/digilent-hs1a.cfg
Start GDB Session: 
set mem inaccessible-by-default off
set $target_riscv = 1
set arch riscv:rv32
set remotetimeout 250

**Comment by TommyMurphyTM1234** [comment]
You really need to attach a verbose OpenOCD log (`openocd -d3 ...`) 

* https://openocd.org/doc/html/Running.html

and a GDB Remote Serial Protocol log:

* https://sourceware.org/gdb/onlinedocs/gdb/Remote-Configuration.html

And maybe also see if basic debugging using the OpenOCD telnet interface works just to eliminate GDB from the picture temporarily:

* https://openocd.org/doc/html/General-Commands.html#General-Commands

**Comment by hparpinel** [comment]
I tried what you suggested from OpenOCD I get the output below but from GDB I dont get anything
xPack Open On-Chip Debugger 0.12.0-01004-g9ea7f3d64-dirty (2023-01-30-15:03)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
User : 3 1 options.c:52 configuration_output_handler(): debug_level: 3
User : 4 1 options.c:52 configuration_output_handler(): 
Debug: 5 1 options.c:233 add_default_dirs(): bindir=/__w/openocd-xpack/openocd-xpack/build/linux-x64/application/bin
Debug: 6 1 options.c:234 add_default_dirs(): pkgdatadir=/__w/openocd-xpack/openocd-xpack/build/linux-x64/application/openocd
Debug: 7 1 options.c:235 add_default_dirs(): exepath=/home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin
Debug: 8 1 options.c:236 add_default_dirs(): bin2data=../openocd
Debug: 9 1 configuration.c:33 add_script_search_dir(): adding /home/bluespec/.config/openocd
Debug: 10 1 configuration.c:33 add_script_search_dir(): adding /home/bluespec/.openocd
Debug: 11 1 configuration.c:33 add_script_search_dir(): adding /home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/../openocd/site
Debug: 12 1 configuration.c:33 add_script_search_dir(): adding /home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/../openocd/scripts
Debug: 13 1 command.c:155 script_debug(): command - gdb_port 3333
Debug: 14 1 command.c:155 script_debug(): command - telnet_port 4444
Debug: 15 1 command.c:155 script_debug(): command - tcl_port 6666
Debug: 16 1 command.c:155 script_debug(): command - ocd_find board/digilent_arty.cfg
Debug: 17 1 configuration.c:88 find_file(): found /home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/../openocd/scripts/board/digilent_arty.cfg
Debug: 18 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'adapter driver' not 'interface'
User : 19 1 command.c:685 handle_echo(): DEPRECATED! use 'adapter driver' not 'interface'
Debug: 20 1 command.c:155 script_debug(): command - adapter driver ftdi
Debug: 21 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi device_desc' not 'ftdi_device_desc'
User : 22 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi device_desc' not 'ftdi_device_desc'
Debug: 23 1 command.c:155 script_debug(): command - ftdi device_desc Digilent USB Device
Debug: 24 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi vid_pid' not 'ftdi_vid_pid'
User : 25 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi vid_pid' not 'ftdi_vid_pid'
Debug: 26 1 command.c:155 script_debug(): command - ftdi vid_pid 0x0403 0x6010
Debug: 27 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi channel' not 'ftdi_channel'
User : 28 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi channel' not 'ftdi_channel'
Debug: 29 1 command.c:155 script_debug(): command - ftdi channel 0
Debug: 30 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi layout_init' not 'ftdi_layout_init'
User : 31 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi layout_init' not 'ftdi_layout_init'
Debug: 32 1 command.c:155 script_debug(): command - ftdi layout_init 0x0088 0x008b
Debug: 33 1 command.c:155 script_debug(): command - reset_config none
Debug: 34 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'adapter speed' not 'adapter_khz'
User : 35 1 command.c:685 handle_echo(): DEPRECATED! use 'adapter speed' not 'adapter_khz'
Debug: 36 1 command.c:155 script_debug(): command - adapter speed 10000
Debug: 37 1 adapter.c:251 adapter_config_khz(): handle adapter khz
Debug: 38 1 adapter.c:215 adapter_khz_to_speed(): convert khz to adapter specific speed value
Debug: 39 1 adapter.c:215 adapter_khz_to_speed(): convert khz to adapter specific speed value
Debug: 40 1 command.c:155 script_debug(): command - ocd_find cpld/xilinx-xc7.cfg
Debug: 41 1 configuration.c:88 find_file(): found /home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/../openocd/scripts/cpld/xilinx-xc7.cfg
Debug: 42 1 command.c:155 script_debug(): command - transport select
Info : 43 1 transport.c:265 jim_transport_select(): auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
Debug: 44 1 command.c:155 script_debug(): command - transport select
Debug: 45 1 command.c:155 script_debug(): command - expr  [ string first "jtag" $_TRANSPORT ] != -1 
Debug: 46 1 command.c:155 script_debug(): command - jtag newtap xc7 tap -irlen 6 -ignore-version -expected-id 0x03622093 -expected-id 0x03620093 -expected-id 0x037C4093 -expected-id 0x0362F093 -expected-id 0x037C8093 -expected-id 0x037C7093 -expected-id 0x037C3093 -expected-id 0x0362E093 -expected-id 0x037C2093 -expected-id 0x0362D093 -expected-id 0x0362C093 -expected-id 0x03632093 -expected-id 0x03631093 -expected-id 0x03636093 -expected-id 0x03647093 -expected-id 0x0364C093 -expected-id 0x03651093 -expected-id 0x03747093 -expected-id 0x03656093 -expected-id 0x03752093 -expected-id 0x03751093 -expected-id 0x03671093 -expected-id 0x036B3093 -expected-id 0x036B7093 -expected-id 0x036BB093 -expected-id 0x036BF093 -expected-id 0x03667093 -expected-id 0x03682093 -expected-id 0x03687093 -expected-id 0x03692093 -expected-id 0x03691093 -expected-id 0x03696093 -expected-id 0x036D5093 -expected-id 0x036D9093 -expected-id 0x036DB093
Debug: 47 1 tcl.c:557 jim_newtap_cmd(): Creating New Tap, Chip: xc7, Tap: tap, Dotted: xc7.tap, 73 params
Debug: 48 1 tcl.c:582 jim_newtap_cmd(): Processing option: -irlen
Debug: 49 1 tcl.c:582 jim_newtap_cmd(): Processing option: -ignore-version
Debug: 50 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 51 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 52 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 53 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 54 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 55 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 56 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 57 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 58 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 59 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 60 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 61 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 62 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 63 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 64 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 65 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 66 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 67 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 68 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 69 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 70 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 71 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 72 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 73 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 74 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 75 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 76 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 77 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 78 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 79 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 80 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 81 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 82 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 83 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 84 1 tcl.c:582 jim_newtap_cmd(): Processing option: -expected-id
Debug: 85 1 core.c:1474 jtag_tap_init(): Created Tap: xc7.tap @ abs position 0, irlen 6, capture: 0x1 mask: 0x3
Debug: 86 1 command.c:155 script_debug(): command - pld device virtex2 xc7.tap 1
Debug: 87 1 command.c:155 script_debug(): command - ocd_find cpld/jtagspi.cfg
Debug: 88 1 configuration.c:88 find_file(): found /home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/../openocd/scripts/cpld/jtagspi.cfg
Debug: 89 1 command.c:155 script_debug(): command - target create xc7.proxy testee -chain-position xc7.tap
Debug: 90 1 target.c:2199 target_free_all_working_areas_restore(): freeing all working areas
Debug: 91 1 command.c:155 script_debug(): command - flash bank xc7.spi jtagspi 0 0 0 0 xc7.proxy 0x02
Debug: 92 1 tcl.c:1305 handle_flash_bank_command(): 'jtagspi' driver usage field missing
User : 93 1 options.c:52 configuration_output_handler(): jtagspi_programUser : 94 1 options.c:52 configuration_output_handler(): 
Debug: 95 1 command.c:155 script_debug(): command - ocd_find interface/ftdi/digilent-hs1a.cfg
Debug: 96 1 configuration.c:88 find_file(): found /home/bluespec/.local/xPacks/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/../openocd/scripts/interface/ftdi/digilent-hs1a.cfg
Debug: 97 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'adapter driver' not 'interface'
User : 98 1 command.c:685 handle_echo(): DEPRECATED! use 'adapter driver' not 'interface'
Debug: 99 1 command.c:155 script_debug(): command - adapter driver ftdi
Warn : 100 1 adapter.c:435 handle_adapter_driver_command(): Interface already configured, ignoring
Debug: 101 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi device_desc' not 'ftdi_device_desc'
User : 102 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi device_desc' not 'ftdi_device_desc'
Debug: 103 1 command.c:155 script_debug(): command - ftdi device_desc Digilent USB Device
Debug: 104 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi vid_pid' not 'ftdi_vid_pid'
User : 105 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi vid_pid' not 'ftdi_vid_pid'
Debug: 106 1 command.c:155 script_debug(): command - ftdi vid_pid 0x0403 0x6010
Debug: 107 1 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi channel' not 'ftdi_channel'
User : 108 1 command.c:685 handle_echo(): DEPRECATED! use 'ftdi channel' not 'ftdi_channel'
Debug: 109 2 command.c:155 script_debug(): command - ftdi channel 0
Debug: 110 2 command.c:155 script_debug(): command - echo DEPRECATED! use 'ftdi layout_init' not 'ftdi_layout_init'
User : 111 2 command.c:685 handle_echo(): DEPRECATED! use 'ftdi layout_init' not 'ftdi_layout_init'
Debug: 112 2 command.c:155 script_debug(): command - ftdi layout_init 0x0088 0x008b
Debug: 113 2 command.c:155 script_debug(): command - reset_config none
User : 114 2 options.c:52 configuration_output_handler(): none separate
User : 115 2 options.c:52 configuration_output_handler(): 
Debug: 116 2 command.c:155 script_debug(): command - echo Started by GNU MCU Eclipse
User : 117 2 command.c:685 handle_echo(): Started by GNU MCU Eclipse
Info : 118 2 server.c:297 add_service(): Listening on port 6666 for tcl connections
Info : 119 2 server.c:297 add_service(): Listening on port 4444 for telnet connections
Debug: 120 2 command.c:155 script_debug(): command - init
Debug: 121 2 command.c:155 script_debug(): command - target init
Debug: 122 2 command.c:155 script_debug(): command - target names
Debug: 123 2 command.c:155 script_debug(): command - xc7.proxy cget -event gdb-flash-erase-start
Debug: 124 2 command.c:155 script_debug(): command - xc7.proxy configure -event gdb-flash-erase-start reset init
Debug: 125 2 command.c:155 script_debug(): command - xc7.proxy cget -event gdb-flash-write-end
Debug: 126 2 command.c:155 script_debug(): command - xc7.proxy configure -event gdb-flash-write-end reset halt
Debug: 127 2 command.c:155 script_debug(): command - xc7.proxy cget -event gdb-attach
Debug: 128 2 command.c:155 script_debug(): command - xc7.proxy configure -event gdb-attach halt 1000
Debug: 129 2 target.c:1657 handle_target_init_command(): Initializing targets...
Debug: 130 2 ftdi.c:654 ftdi_initialize(): ftdi interface using shortest path jtag state transitions
Debug: 131 7 mpsse.c:412 mpsse_purge(): -
Debug: 132 7 mpsse.c:693 mpsse_loopback_config(): off
Debug: 133 7 mpsse.c:738 mpsse_set_frequency(): target 10000000 Hz
Debug: 134 7 mpsse.c:730 mpsse_rtck_config(): off
Debug: 135 7 mpsse.c:719 mpsse_divide_by_5_config(): off
Debug: 136 7 mpsse.c:699 mpsse_set_divisor(): 2
Debug: 137 7 mpsse.c:762 mpsse_set_frequency(): actually 10000000 Hz
Debug: 138 7 adapter.c:215 adapter_khz_to_speed(): convert khz to adapter specific speed value
Debug: 139 7 adapter.c:219 adapter_khz_to_speed(): have adapter set up
Debug: 140 7 mpsse.c:738 mpsse_set_frequency(): target 10000000 Hz
Debug: 141 7 mpsse.c:730 mpsse_rtck_config(): off
Debug: 142 7 mpsse.c:719 mpsse_divide_by_5_config(): off
Debug: 143 7 mpsse.c:699 mpsse_set_divisor(): 2
Debug: 144 7 mpsse.c:762 mpsse_set_frequency(): actually 10000000 Hz
Info : 145 7 ftdi.c:279 ftdi_speed(): ftdi: if you experience problems at higher adapter clocks, try the command "ftdi tdo_sample_edge falling"
Debug: 146 7 adapter.c:215 adapter_khz_to_speed(): convert khz to adapter specific speed value
Debug: 147 7 adapter.c:219 adapter_khz_to_speed(): have adapter set up
Info : 148 7 adapter.c:179 adapter_init(): clock speed 10000 kHz
Debug: 149 7 openocd.c:134 handle_init_command(): Debug Adapter init complete
Debug: 150 7 command.c:155 script_debug(): command - transport init
Debug: 151 7 transport.c:219 handle_transport_init(): handle_transport_init
Debug: 152 7 core.c:830 jtag_add_reset(): SRST line released
Debug: 153 7 core.c:855 jtag_add_reset(): TRST line released
Debug: 154 7 core.c:328 jtag_call_event_callbacks(): jtag event: TAP reset
Debug: 155 7 command.c:155 script_debug(): command - jtag arp_init
Debug: 156 7 core.c:1509 jtag_init_inner(): Init JTAG chain
Debug: 157 7 core.c:328 jtag_call_event_callbacks(): jtag event: TAP reset
Debug: 158 7 core.c:1234 jtag_examine_chain(): DR scan interrogation for IDCODE/BYPASS
Debug: 159 7 core.c:328 jtag_call_event_callbacks(): jtag event: TAP reset
Info : 160 8 core.c:1133 jtag_examine_chain_display(): JTAG tap: xc7.tap tap/device found: 0x13631093 (mfg: 0x049 (Xilinx), part: 0x3631, ver: 0x1)
Debug: 161 8 core.c:1364 jtag_validate_ircapture(): IR capture validation scan
Debug: 162 8 core.c:1421 jtag_validate_ircapture(): xc7.tap: IR capture 0x35
Debug: 163 8 command.c:155 script_debug(): command - dap init
Debug: 164 8 arm_dap.c:97 dap_init_all(): Initializing all DAPs ...
Debug: 165 8 openocd.c:151 handle_init_command(): Examining targets...
Debug: 166 8 target.c:1843 target_call_event_callbacks(): target event 19 (examine-start) for core xc7.proxy
Debug: 167 8 target.c:1843 target_call_event_callbacks(): target event 21 (examine-end) for core xc7.proxy
Debug: 168 8 command.c:155 script_debug(): command - flash init
Debug: 169 8 tcl.c:1375 handle_flash_init_command(): Initializing flash devices...
Debug: 170 8 command.c:155 script_debug(): command - nand init
Debug: 171 8 tcl.c:487 handle_nand_init_command(): Initializing NAND devices...
Debug: 172 8 command.c:155 script_debug(): command - pld init
Debug: 173 8 pld.c:194 handle_pld_init_command(): Initializing PLDs...
Debug: 174 8 command.c:155 script_debug(): command - tpiu init
Debug: 175 8 gdb_server.c:3819 gdb_target_add_one(): skip gdb server for target xc7.proxy

**Comment by TommyMurphyTM1234** [comment]
You're not using the latest OpenOCD built from this repo.
You should do that before reporting issues here.
You should also address the deprecated warnings in your OpenOCD scripts.
And you should also clarify the details of your target FPGA RISC-V implementation, how you have verified that the debug block is fully functional, what scripts you are using for debugging etc.
There are too many unknowns for anybody to provide any meaningful comment.

**Comment by TommyMurphyTM1234** [comment]
> The board I am working with is an Arty A7 100T. The board is programmed with the core; 

What core/RISC-V implementation?

**Comment by hparpinel** [comment]
I have the latest OpenOCD build. I was just trying different settings to figure out what was going on.
Update for future reference: I believe the issue was that my Ubuntu machine had a gdb installation and might have been intercepting the connection. I removed that installation and now its working.
Thanks for your help

**Comment by TommyMurphyTM1234** [comment]
> I have the latest OpenOCD build. 

This is not a build of the latest `riscv-openocd`.

> ```
> xPack Open On-Chip Debugger 0.12.0-01004-g9ea7f3d64-dirty (2023-01-30-15:03)
> ```

> I was just trying different settings to figure out what was going on. Update for future reference: I believe the issue was that my Ubuntu machine had a gdb installation and might have been intercepting the connection. I removed that installation and now its working. Thanks for your help

Ok, can you close the issue if it's resolved so, please?
