### ISSUE TITLE
Jtag-HS3 testing

### ISSUE THREAD

**Issue by Wen-Sheng** [riscv/riscv-openocd#839]
Hi, if I just want to use HS3 without SRST, how should I modify CFG (SRST is connected to high potential)

**Comment by TommyMurphyTM1234** [comment]
`reset_config none`?
Assuming that neither `srst` nor `trst` are available.

* https://openocd.org/doc/html/Reset-Configuration.html

**Comment by Wen-Sheng** [comment]
According to your suggestion, the problem has been solved,
Thanks for your help ~~~~

**Comment by TommyMurphyTM1234** [comment]
> According to your suggestion, the problem has been solved, Thanks for your help ~~~~

Great. You're welcome.
