### ISSUE TITLE
Setting of tdata registers: Difference between the specification and the implementation in riscv-openocd

### ISSUE THREAD

**Issue by MarekVCodasip** [riscv/riscv-openocd#870]
There seems to be an inconsistency between the debug specification and the implementation here:
https://github.com/riscv/riscv-openocd/blob/470c2a402c64e3cfc3bf51f950cb330b93d52b65/src/target/riscv/riscv.c#L571

The current specification (https://github.com/riscv/riscv-debug-spec/blob/9001957c1067ab76c7abc6249635f21539391fc8/riscv-debug-stable.pdf), in section 5.6 says that:
- tdata1 should first be written to 0
- tdata2 and tdata3 should have the desired values written to
- tdata1 should be written as last

The implementation of set_trigger does not seem to follow it, can you confirm? Thanks.

**Comment by timsifive** [comment]
You are right. That should be improved. I'm not currently aware of any hardware that actually requires the behavior in the spec.
