### ISSUE TITLE
which openOCD is better to use this one or the "Official OpenOCD Read-Only Mirror (no pull requests) "

### ISSUE THREAD

**Issue by InspireSemi** [riscv/riscv-openocd#881]
How often are these two synced?  Is it better to use this one or the other one?

**Comment by TommyMurphyTM1234** [comment]
> How often are these two synced?

See here:

* https://github.com/riscv/riscv-openocd/issues/790

> Is it better to use this one or the other one?

"Better" in what way exactly?

If you want the latest updates for RISC-V support then use this one.
If you want the latest updates for other targets and architecturally neutral parts of OpenOCD then use upstream.
If you want both then you'll have to resolve the differences/merges yourself as long as they're out of sync.

**Comment by TommyMurphyTM1234** [comment]
Not sure that this issue needs to stay open?

**Comment by InspireSemi** [comment]
Yes you can choose this

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TommyMurphyTM1234** [comment]
Can't you close it?
I can't (don't have the repo privileges) and I'm sure that @timsifive has enough to do.
Thanks.

**Comment by InspireSemi** [comment]
Closed
