### ISSUE TITLE
Incorect register indices returned by riscv013_debug_buffer_register

### ISSUE THREAD

**Issue by command-paul** [riscv/riscv-openocd#89]
riscv013_debug_buffer_register ::
```c
int riscv013_debug_buffer_register(struct target *target, riscv_addr_t addr)
{
	if (addr >= riscv013_data_addr(target))
		return DMI_DATA0 + (addr - riscv013_data_addr(target)) / 4;
	else
		return DMI_PROGBUF0 + (addr - riscv013_progbuf_addr(target)) / 4;
}
```

An incorrect DM Register index is returned when Data registers are not memory mapped (HartInfo[dataAccess] = 0) , 
The non assignment of the program buffer address to the riscv_info structure 
causes the else routine to fail at 
```c
assert(info->progbuf_addr != -1); (riscv-013.c :1974)
```
I`ve worked my way around this for our Shakti Cores by bypassing the 
```c
if (addr >= riscv013_data_addr(target));
```
condition , and updating progbuf_addr in the structure .

**Comment by timsifive** [comment]
Unfortunately OpenOCD currently really doesn't work with anything not
memory-mapped. Fixing this is on my TODO list, but other stuff keeps coming
up. In the meantime it sounds like you have a reasonable work-around,
although not something that I'd want to add to the codebase like that.

Is there any way for me to work with the target you have? An FPGA image I
can use on an Arty board would be ideal.

Tim

**Comment by command-paul** [comment]
@neelgala

**Comment by timsifive** [comment]
I've opened #112 to track OpenOCD supporting targets without a program buffer.
