### ISSUE TITLE
execute_fence does not handle errors

### ISSUE THREAD

**Issue by aap-sc** [riscv/riscv-openocd#933]
Currently execute_fence (from riscv-013.c) is structured as follows:

```
if (has_sufficient_progbuf(target, 3)) {                                                        
   riscv_program_init(&program, target);                                                         
   riscv_program_fence_rw_rw(&program);                                                          
   riscv_program_fence_i(&program);                                                              
   result = riscv_program_exec(&program, target);                                                
   if (result != ERROR_OK)                                                                       
       LOG_TARGET_DEBUG(target, "Unable to execute pre-fence");                                    
  return ERROR_OK;
} 

if (has_sufficient_progbuf(target, 2)) {
 ...
  return ERROR_OK;
}
return ERROR_FAIL
```

As you can see - this function always return `ERROR_OK` if there is enough space in progbuf. I've checked the codebase and it seems that it was this way for a while now (even before  https://github.com/riscv/riscv-openocd/pull/903 fixup).

Now, I don't quite understand why is the error ignored? @timsifive do you have any ideas/would you kindly clarify this situation? Is it for compatibility with targets that do not have `fence` - like instructions or is it a bug?

NOTE: the reason I'm asking the question is that recently I've encountered a HW that under certain conditions returned an error during execution of `fence` - I was thinking about adding a more strict diagnostics for this case.

**Comment by timsifive** [comment]
`fence.i` is not required to be implemented, and if it isn't, then there really isn't anything we can do about it. Certainly we don't want to report that to the user every time we attempt to executed it. That's just annoying. We could report the first failure and be silent from then on.

**Comment by TommyMurphyTM1234** [comment]
This issue might also be relevant here?

* https://github.com/riscv/riscv-openocd/issues/415

And this

* https://github.com/riscv/riscv-openocd/issues/893#issuecomment-1644579151

**Comment by aap-sc** [comment]
@TommyMurphyTM1234 yes, #415 has a direct relevance to this. Thank you! 

@timsifive , regarding this:

> fence.i is not required to be implemented, and if it isn't, then there really isn't anything we can do about it. 

Ok, got it.

> We could report the first failure and be silent from then on.

Well... I think that `LOG_TARGET_DEBUG` is not that annoying so it can be left as is IMHO. However, in my original message I state that:

>  I was thinking about adding a more strict diagnostics for this case.

By this I mean I'd like to modify `execute_fence` function to return a proper error, so callers (like `write_memory`) could identify potential errors. The fact that we don't have a simple way to figure out  if `i.fence` is supported is disappointing. However, I have few ideas how this can be done and would like to discuss if these are reasonable:

- Option "a".

Modify `riscv_program_exec` to return (as an output parameter) an additional status indicating the reason for the failure, so we can differentiate between an exception during execution of program buffer and some other errors. Then, `execute_fence` could query this status and return `ERROR_FAIL` if `riscv_program_exec` fails for some other reason (other than encountering an exception).

- Option "b".

Introduce an additional target configuration parameter, something like `riscv_require_ifence` (which  should be true by default) and just query these options before deciding if we even need to issue the fence.

- Option "c" (I don't like it).

We could try to issue the fence during `examine` . And analyze the status of the operation (it requires Option "a" to be implemented). However, I don't like this approach since it renders our `examine` procedure even more invasive - and In think we should minimize the impact of the `examine` on the system.


My preference would be to implement "Option b" since the implementation is rather straightforward without any juggling with error codes. Targets that don't support fence operation will have to bite the bullet and modify their configuration files. We can add a big ugly/pretty error message to help with that.  

If anyone has an opinion on the matter, please do share.

**Comment by MarekVCodasip** [comment]
In our opinion (consulted with @JanMatCodasip): 

- We don't like the option "c" either due to the invasivity.
- For option "a": We believe having different return codes for riscv_program_exec() is a good general improvement (ERROR_PROGBUF_TOO_SMALL, ERROR_PROGBUF_EXCEPTION, etc.). We would not prefer to add additional output parameter for this. Return code seems sufficient and is simpler to use.
- Option "b" seems OK to us.
- We have one more option "d" for consideration. It is described below.

Option "d":
Keep track if fence_i is supported on the target (three state value YES/NO/MAYBE). Upon the first attempt to execute fence_i, detect if its supported and store the outcome. If it's not supported, log a warning (which will be shown only once).
This option can go together with option "a".

**Comment by aap-sc** [comment]
> We would not prefer to add additional output parameter for this. Return code seems sufficient and is simpler to use.

Regarding the error code. We have a major problem with that, since most of the functions that return errors use `int` values that are defined mostly in target-independent code. This may create a problem with maintaining these: 

1.  our riscv-(progbuf) specific codes may overlap with some target-independent value
2.  the rest of the codebase will operate on target-independent `errors` and figuring out what is what may be problematic.

Thus I feel that if we want to introduce special handling for progbuf-specific errors, these errors should be a separate type (likely a structure) to avoid confusion. Returning the error code as an output parameter may be beneficial for code uniformity, however I can see that having such output parameters may affect readability (so if we end up with choosing option "d", we should consider both implementations).

**Comment by en-sc** [comment]
Regarding the option "a":
There is the `cmderr`  field in `riscv013_info_t` which contains the most recent value of `abstractcs.cmderr` (set in `execute_abstract_command`). This allows one to check if an exception has occurred without introducing additional return codes. However, it should be noted, that if such an approach is used, the value of `info->cmderr` should be reset prior to call to `riscv_program_exec`.

**Comment by JanMatCodasip** [comment]
> Regarding the option "a": There is the cmderr field in riscv013_info_t ...

Communicating function arguments / results through (per-target) global variables is not a good pattern. If possible, I would like to avoid it.

**Comment by JanMatCodasip** [comment]
> our riscv-(progbuf) specific codes may overlap with some target-independent value

I assume that if we claim certain unique error code, no other part of OpenOCD (no other target and also no target independent) should use it.

In another words, there should not be any overlap, provided that other OpenOCD developers do check the uniqueness of their newly introduced error codes.

**Comment by aap-sc** [comment]
> In another words, there should not be any overlap, provided that other OpenOCD developers do check the uniqueness of their newly introduced error codes.

The problem is that upstream OpenOCD changes are not synchronized. I doubt that OpenOCD developers from https://openocd.org/ will keep these in-sync. So this is a recipe for potential issue in future. Alternative solution will be to return a structure with the necessary statuses from progbuf-related functions. A little cumbersome, but no pointers are involved.

~~In any case - the finding @en-sc may be useful to address this.~~ Oh... you were talking about this comment.

**Comment by JanMatCodasip** [comment]
> The problem is that upstream OpenOCD changes are not synchronized. 

That's right, but not a big issue. When submitting code from riscv-openocd to vanilla upstream, we just need to check our new error codes (and in the unlikely event of a collision re-number them).

**Comment by aap-sc** [comment]
> When submitting code from riscv-openocd to vanilla upstream, we just need to check our new error codes (and in the unlikely event of a collision re-number them).

This implies that we will remember about this. Spoiler: we won't  :)

**Comment by timsifive** [comment]
My point wasn't that it's hard to detect whether `fence.i` succeeds or not. The point is that it doesn't matter, because the debugger has no alternative. Either it works, which is good for the user. Or it doesn't work because the hardware doesn't support it, and then it sucks for the user (potentially, if there are multiple harts, and caches, and no cache snooping).

As a general principle it's good to have the code be aware of when errors happen, and I would be OK with a change that makes it so. But it's going to have no effect on the user experience at all.

**Comment by aap-sc** [comment]
> But it's going to have no effect on the user experience at all.

In our specific case the problem is that (due to some bug in HW) the `ifence` hangs unexpectedly (abstract command execution results in timeout), but `load_image` function still reports success. I want the debugger to report an error in such cases (thus the ticket and discussion)

**Comment by timsifive** [comment]
Hmm... But how can the debugger distinguish between `fence.i` not being implemented, and it leading to an unexpected hang? I wouldn't want to report an error simply because it isn't implemented. Is there a mechanism to determine whether `fence.i` is implemented without trying to execute the instruction?

**Comment by aap-sc** [comment]
> Hmm... But how can the debugger distinguish between fence.i not being implemented, and it leading to an unexpected hang? I wouldn't want to report an error simply because it isn't implemented. Is there a mechanism to determine whether fence.i is implemented without trying to execute the instruction?

Probably, I've formulated the issue incorrectly.

To detect that a situation that the fence.i is not implemented it is enough (I think) to identify a situation when the result of a corresponding abstract command indicates and exception.

By "hang" I mean a situation when execution of a corresponding abstract command results in timeout.

**Comment by TommyMurphyTM1234** [comment]
I could have sworn that somebody else (elsewhere?) suggested adding a RISC-V specific boolean attribute and command with which OpenOCD could be told that the target did not support `fence.i` and then not try to use it. Obviously this attribute would be "true" by default for the de facto behaviour. But somebody with a target that doesn't support `fence.i` could use the command to set the attribute to "false". Wouldn't that be a happy medium given that it seems like there's no simple way to dynamically detect target support for `fencei.i`?

**Comment by aap-sc** [comment]
> with which OpenOCD could be told that the target did not support fence.i and then not try to use

this is "option b" :).

**Comment by TommyMurphyTM1234** [comment]
> > with which OpenOCD could be told that the target did not support fence.i and then not try to use
> 
> this is "option b" :).

Thanks! My bad for not scrolling back far enough! :-D

**Comment by timsifive** [comment]
> To detect that a situation that the fence.i is not implemented it is enough (I think) to identify a situation when the result of a corresponding abstract command indicates and exception.

Ah. That makes sense. If the command regularly fails that probably means `fence.i` is not implemented and there is no reason to bother the user. But a timeout error definitely indicates there is a problem that the user should be notified about.

**Comment by aap-sc** [comment]
https://github.com/riscv/riscv-openocd/pull/964 addressed this issue. Decided to go with option "a" for now (see https://github.com/riscv/riscv-openocd/issues/933#issuecomment-1757465562 )
