### ISSUE TITLE
abstractcs timeouts should not be hard-coded

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-openocd#96]
There is a timeout WALL_CLOCK_TIMEOUT for polling abstractcs.busy. This shouldn't be compiled in, as this timeout is going to be very different when interacting with a simulation target vs a HW target. Similarly, WALL_CLOCK_RESET_TIMEOUT should not be compiled in. We should create riscv target-specific commands for these items. 

I know it is a goal of this OpenOCD implementation that user should not have to specify a lot of knobs, but one could pretty easily give the user instructions on what to do if they *are* hitting these timeouts.

**Comment by timsifive** [comment]
Can this be closed now that #100 merged?

**Comment by mwachs5** [comment]
Yes thanks
