### ISSUE TITLE
'riscv set_pfrefer_sba on' can't be executed.

### ISSUE THREAD

**Issue by hyperion009** [riscv/riscv-openocd#965]
Hi 
I am trying to connect SimJTAG in Rockchip to OpenOCD by the following command(https://github.com/chipsalliance/rocket-chip/blob/master/scripts/RocketSim.cfg):
setenv JTAG_VPI_PORT 36054; setenv JTAG_DTM_ENABLE_SBA on; openocd -f RocketSim.cfg -d -l log
However, Got a issue:
![image](https://github.com/riscv/riscv-openocd/assets/30075118/751b7ae6-31dd-4eb3-bf4f-4fb01e8af46d)
Is there a real issue? How to fix/workaround this one?

thanks

**Comment by TommyMurphyTM1234** [comment]
`riscv set_prefer_sba` was removed by this PR:

* https://github.com/riscv/riscv-openocd/pull/884#issuecomment-1655651193

Your `Rocketsim.cfg` script is using a command that is no longer supported.

**Comment by hyperion009** [comment]
@TommyMurphyTM1234  thanks Tommy for your update.
