### ISSUE TITLE
Can OpenOCD detect the JLINK serial number automatically?

### ISSUE THREAD

**Issue by panciyan** [riscv/riscv-openocd#987]
I can select JLINK by configure command: adapter serial
Can OpenOCD detect the JLINK serial number automatically?

**Comment by JanMatCodasip** [comment]
This is a question that is unrelated to RISC-V support in OpenOCD.

Therefore, please ask in the official OpenOCD channels (mailing list or IRC): https://openocd.org/pages/discussion.html

Closing this issue.
